CREATE TABLE [Fj_servindustrias].[Af_Poliza_x_AF] (
    [IdEmpresa]                      INT           NOT NULL,
    [IdPoliza]                       NUMERIC (18)  NOT NULL,
    [IdProveedor]                    NUMERIC (18)  NOT NULL,
    [IdCentroCosto]                  VARCHAR (20)  NULL,
    [IdCentroCosto_sub_centro_costo] VARCHAR (20)  NULL,
    [cod_poliza]                     VARCHAR (50)  NOT NULL,
    [fecha]                          DATETIME      NOT NULL,
    [observacion]                    VARCHAR (250) NOT NULL,
    [fecha_vigencia_desde]           DATETIME      NOT NULL,
    [fecha_vigencia_hasta]           DATETIME      NOT NULL,
    [num_cuotas]                     INT           NOT NULL,
    [valor_cuota]                    FLOAT (53)    NOT NULL,
    [fecha_1era_cuota]               DATETIME      NOT NULL,
    [suma_asegurada]                 FLOAT (53)    NOT NULL,
    [total_meses]                    INT           NOT NULL,
    [subtotal]                       FLOAT (53)    NOT NULL,
    [porc_iva]                       FLOAT (53)    NOT NULL,
    [iva]                            FLOAT (53)    NOT NULL,
    [Total]                          FLOAT (53)    NOT NULL,
    [IdUsuario]                      VARCHAR (20)  NULL,
    [Fecha_Transac]                  DATETIME      NULL,
    [IdUsuarioUltMod]                VARCHAR (20)  NULL,
    [Fecha_UltMod]                   DATETIME      NULL,
    [IdUsuarioUltAnu]                VARCHAR (20)  NULL,
    [Fecha_UltAnu]                   DATETIME      NULL,
    [nom_pc]                         VARCHAR (50)  NULL,
    [ip]                             VARCHAR (25)  NULL,
    [MotivoAnulacion]                NCHAR (10)    NULL,
    [Estado]                         CHAR (1)      NOT NULL,
    [subtotal_noIva]                 FLOAT (53)    NULL,
    [pago_contado]                   FLOAT (53)    NULL,
    CONSTRAINT [PK_Af_Poliza_x_AF] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdPoliza] ASC, [IdProveedor] ASC),
    CONSTRAINT [FK_Af_Poliza_x_AF_cp_proveedor] FOREIGN KEY ([IdEmpresa], [IdProveedor]) REFERENCES [dbo].[cp_proveedor] ([IdEmpresa], [IdProveedor])
);

