CREATE TABLE [dbo].[ba_Inversion] (
    [IdEmpresa]       INT           NOT NULL,
    [IdInversion]     NUMERIC (18)  NOT NULL,
    [Cod_Inversion]   VARCHAR (50)  NOT NULL,
    [IdBanco]         INT           NOT NULL,
    [Fecha]           DATE          NOT NULL,
    [Plazo]           INT           NOT NULL,
    [Fecha_Vct]       DATE          NOT NULL,
    [Monto]           FLOAT (53)    NOT NULL,
    [Tasa]            FLOAT (53)    NOT NULL,
    [Por_Retencion]   FLOAT (53)    NOT NULL,
    [Valor_retencion] FLOAT (53)    NOT NULL,
    [Otros]           FLOAT (53)    NOT NULL,
    [Tasa_interes]    FLOAT (53)    NOT NULL,
    [Valor_interes]   FLOAT (53)    NOT NULL,
    [Capital]         FLOAT (53)    NOT NULL,
    [Total_recibir]   FLOAT (53)    NOT NULL,
    [Observacion]     VARCHAR (250) NOT NULL,
    [Estado]          CHAR (1)      NOT NULL,
    [IdUsuario]       VARCHAR (20)  NOT NULL,
    [Fecha_Transac]   DATETIME      NOT NULL,
    [IdUsuarioUltMod] VARCHAR (20)  NULL,
    [Fecha_UltMod]    DATETIME      NULL,
    [IdUsuarioUltAnu] VARCHAR (20)  NULL,
    [Fecha_UltAnu]    DATETIME      NULL,
    [nom_pc]          VARCHAR (50)  NULL,
    [ip]              VARCHAR (25)  NULL,
    [MotiAnula]       VARCHAR (200) NULL,
    CONSTRAINT [PK_ba_Inversion] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdInversion] ASC),
    CONSTRAINT [FK_ba_Inversion_ba_Banco_Cuenta] FOREIGN KEY ([IdEmpresa], [IdBanco]) REFERENCES [dbo].[ba_Banco_Cuenta] ([IdEmpresa], [IdBanco])
);

