CREATE TABLE [dbo].[ba_prestamo] (
    [IdEmpresa]         INT           NOT NULL,
    [IdPrestamo]        NUMERIC (18)  NOT NULL,
    [CodPrestamo]       VARCHAR (50)  NOT NULL,
    [IdBanco]           INT           NOT NULL,
    [IdMetCalc]         VARCHAR (50)  NULL,
    [IdMotivo_Prestamo] VARCHAR (50)  NOT NULL,
    [Estado]            CHAR (1)      NOT NULL,
    [Fecha]             DATETIME      NOT NULL,
    [MontoSol]          FLOAT (53)    NOT NULL,
    [TasaInteres]       FLOAT (53)    NOT NULL,
    [TotalPrestamo]     FLOAT (53)    NOT NULL,
    [NumCuotas]         INT           NOT NULL,
    [IdTipo_Pago]       VARCHAR (50)  NOT NULL,
    [Fecha_PriPago]     DATETIME      NOT NULL,
    [Observacion]       VARCHAR (250) NOT NULL,
    [IdUsuario]         VARCHAR (20)  NOT NULL,
    [Fecha_Transac]     DATETIME      NOT NULL,
    [IdUsuarioUltMod]   VARCHAR (20)  NULL,
    [Fecha_UltMod]      DATETIME      NULL,
    [IdUsuarioUltAnu]   VARCHAR (20)  NULL,
    [Fecha_UltAnu]      DATETIME      NULL,
    [nom_pc]            VARCHAR (50)  NULL,
    [ip]                VARCHAR (25)  NULL,
    [MotiAnula]         VARCHAR (200) NULL,
    [IdTipoFlujo]       NUMERIC (18)  NULL,
    [IdCtaCble]         VARCHAR (20)  NULL,
    [Pago_contado]      FLOAT (53)    NULL,
    [IdCliente]         NUMERIC (9)   NULL,
    CONSTRAINT [PK_ba_prestamo] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdPrestamo] ASC),
    CONSTRAINT [FK_ba_prestamo_ba_Catalogo] FOREIGN KEY ([IdMetCalc]) REFERENCES [dbo].[ba_Catalogo] ([IdCatalogo]),
    CONSTRAINT [FK_ba_prestamo_ba_Catalogo1] FOREIGN KEY ([IdMotivo_Prestamo]) REFERENCES [dbo].[ba_Catalogo] ([IdCatalogo]),
    CONSTRAINT [FK_ba_prestamo_ba_Catalogo2] FOREIGN KEY ([IdTipo_Pago]) REFERENCES [dbo].[ba_Catalogo] ([IdCatalogo]),
    CONSTRAINT [FK_ba_prestamo_ba_TipoFlujo] FOREIGN KEY ([IdEmpresa], [IdTipoFlujo]) REFERENCES [dbo].[ba_TipoFlujo] ([IdEmpresa], [IdTipoFlujo]),
    CONSTRAINT [FK_ba_prestamo_ct_plancta] FOREIGN KEY ([IdEmpresa], [IdCtaCble]) REFERENCES [dbo].[ct_plancta] ([IdEmpresa], [IdCtaCble])
);

