CREATE TABLE [dbo].[ba_transferencia] (
    [IdTransferencia]    NUMERIC (18)  NOT NULL,
    [IdEmpresa_origen]   INT           NOT NULL,
    [IdCbteCble_origen]  NUMERIC (18)  NOT NULL,
    [IdTipocbte_origen]  INT           NOT NULL,
    [IdEmpresa_destino]  INT           NOT NULL,
    [IdCbteCble_destino] NUMERIC (18)  NOT NULL,
    [IdTipocbte_destino] INT           NOT NULL,
    [IdBanco_origen]     INT           NOT NULL,
    [IdBanco_destino]    INT           NOT NULL,
    [tr_observacion]     VARCHAR (700) NOT NULL,
    [tr_valor]           FLOAT (53)    NOT NULL,
    [tr_fecha]           DATE          NOT NULL,
    [tr_estado]          VARCHAR (1)   NULL,
    [IdUsuario]          VARCHAR (50)  NULL,
    [IdUsuario_Anu]      NCHAR (10)    NULL,
    [FechaAnulacion]     DATETIME      NULL,
    [Fecha_Transac]      DATETIME      NULL,
    [Fecha_UltMod]       DATETIME      NULL,
    [IdUsuarioUltMod]    VARCHAR (50)  NULL,
    [ip]                 VARCHAR (25)  NULL,
    [nom_pc]             VARCHAR (50)  NULL,
    [tr_MotivoAnulacion] VARCHAR (250) NULL,
    CONSTRAINT [PK_ba_transferencia] PRIMARY KEY CLUSTERED ([IdTransferencia] ASC, [IdEmpresa_origen] ASC),
    CONSTRAINT [FK_ba_transferencia_ba_Banco_Cuenta] FOREIGN KEY ([IdEmpresa_origen], [IdBanco_origen]) REFERENCES [dbo].[ba_Banco_Cuenta] ([IdEmpresa], [IdBanco]),
    CONSTRAINT [FK_ba_transferencia_ba_Banco_Cuenta1] FOREIGN KEY ([IdEmpresa_destino], [IdBanco_destino]) REFERENCES [dbo].[ba_Banco_Cuenta] ([IdEmpresa], [IdBanco]),
    CONSTRAINT [FK_ba_transferencia_ba_Cbte_Ban] FOREIGN KEY ([IdEmpresa_origen], [IdCbteCble_origen], [IdTipocbte_origen]) REFERENCES [dbo].[ba_Cbte_Ban] ([IdEmpresa], [IdCbteCble], [IdTipocbte]),
    CONSTRAINT [FK_ba_transferencia_ba_Cbte_Ban1] FOREIGN KEY ([IdEmpresa_destino], [IdCbteCble_destino], [IdTipocbte_destino]) REFERENCES [dbo].[ba_Cbte_Ban] ([IdEmpresa], [IdCbteCble], [IdTipocbte])
);

