CREATE TABLE [dbo].[com_solicitud_compra] (
    [IdEmpresa]           INT            NOT NULL,
    [IdSucursal]          INT            NOT NULL,
    [IdSolicitudCompra]   NUMERIC (18)   NOT NULL,
    [NumDocumento]        VARCHAR (50)   NOT NULL,
    [IdSolicitante]       NUMERIC (18)   NOT NULL,
    [IdComprador]         NUMERIC (18)   NOT NULL,
    [IdDepartamento]      NUMERIC (18)   NOT NULL,
    [fecha]               DATETIME       NOT NULL,
    [plazo]               INT            NOT NULL,
    [fecha_vtc]           DATETIME       NOT NULL,
    [observacion]         VARCHAR (1000) NOT NULL,
    [Estado]              CHAR (1)       NOT NULL,
    [Fecha_Transac]       DATETIME       NULL,
    [Fecha_UltMod]        DATETIME       NULL,
    [IdUsuarioUltMod]     CHAR (20)      NULL,
    [FechaHoraAnul]       DATETIME       NULL,
    [IdUsuarioUltAnu]     CHAR (20)      NULL,
    [MotivoAnulacion]     VARCHAR (500)  NULL,
    [IdEstadoAprobacion]  VARCHAR (25)   NULL,
    [IdUsuarioAprobo]     VARCHAR (25)   NULL,
    [MotivoAprobacion]    VARCHAR (25)   NULL,
    [FechaHoraAprobacion] DATETIME       NULL,
    CONSTRAINT [PK_com_solicitud_compra] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdSucursal] ASC, [IdSolicitudCompra] ASC),
    CONSTRAINT [FK_com_solicitud_compra_com_catalogo] FOREIGN KEY ([IdEstadoAprobacion]) REFERENCES [dbo].[com_catalogo] ([IdCatalogocompra]),
    CONSTRAINT [FK_com_solicitud_compra_com_comprador] FOREIGN KEY ([IdEmpresa], [IdComprador]) REFERENCES [dbo].[com_comprador] ([IdEmpresa], [IdComprador]),
    CONSTRAINT [FK_com_solicitud_compra_com_departamento] FOREIGN KEY ([IdEmpresa], [IdDepartamento]) REFERENCES [dbo].[com_departamento] ([IdEmpresa], [IdDepartamento])
);

