CREATE TABLE [dbo].[cp_Aprobacion_Ing_Bod_x_OC_det] (
    [IdEmpresa]                          INT          NOT NULL,
    [IdAprobacion]                       NUMERIC (18) NOT NULL,
    [Secuencia]                          INT          NOT NULL,
    [IdEmpresa_Ing_Egr_Inv]              INT          NOT NULL,
    [IdSucursal_Ing_Egr_Inv]             INT          NOT NULL,
    [IdNumMovi_Ing_Egr_Inv]              NUMERIC (18) NOT NULL,
    [Secuencia_Ing_Egr_Inv]              INT          NOT NULL,
    [IdProducto]                         NUMERIC (18) NULL,
    [Cantidad]                           FLOAT (53)   NOT NULL,
    [Costo_uni]                          FLOAT (53)   NOT NULL,
    [por_descuento]                      FLOAT (53)   NULL,
    [Cost_uni_final]                     FLOAT (53)   NULL,
    [Descuento]                          FLOAT (53)   NOT NULL,
    [SubTotal]                           FLOAT (53)   NOT NULL,
    [IdCod_Impuesto_Iva]                 VARCHAR (25) NULL,
    [PorIva]                             FLOAT (53)   NOT NULL,
    [valor_Iva]                          FLOAT (53)   NOT NULL,
    [Total]                              FLOAT (53)   NOT NULL,
    [IdCtaCble_Gasto]                    VARCHAR (20) NOT NULL,
    [IdCtaCble_IVA]                      VARCHAR (20) NULL,
    [IdCentro_Costo_x_Gasto_x_cxp]       VARCHAR (20) NULL,
    [IdCentroCosto_sub_centro_costo_cxp] VARCHAR (20) NULL,
    [IdMovi_inven_tipo_Ing_Egr_Inv]      INT          NOT NULL,
    [IdUnidadMedida]                     VARCHAR (25) NULL,
    CONSTRAINT [PK_cp_Aprobacion_Ing_Bod_x_OC_det] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdAprobacion] ASC, [Secuencia] ASC),
    CONSTRAINT [FK_cp_Aprobacion_Ing_Bod_x_OC_det_cp_Aprobacion_Ing_Bod_x_OC] FOREIGN KEY ([IdEmpresa], [IdAprobacion]) REFERENCES [dbo].[cp_Aprobacion_Ing_Bod_x_OC] ([IdEmpresa], [IdAprobacion]),
    CONSTRAINT [FK_cp_Aprobacion_Ing_Bod_x_OC_det_ct_centro_costo] FOREIGN KEY ([IdEmpresa], [IdCentro_Costo_x_Gasto_x_cxp]) REFERENCES [dbo].[ct_centro_costo] ([IdEmpresa], [IdCentroCosto]),
    CONSTRAINT [FK_cp_Aprobacion_Ing_Bod_x_OC_det_ct_centro_costo_sub_centro_costo] FOREIGN KEY ([IdEmpresa], [IdCentro_Costo_x_Gasto_x_cxp], [IdCentroCosto_sub_centro_costo_cxp]) REFERENCES [dbo].[ct_centro_costo_sub_centro_costo] ([IdEmpresa], [IdCentroCosto], [IdCentroCosto_sub_centro_costo]),
    CONSTRAINT [FK_cp_Aprobacion_Ing_Bod_x_OC_det_ct_plancta] FOREIGN KEY ([IdEmpresa], [IdCtaCble_Gasto]) REFERENCES [dbo].[ct_plancta] ([IdEmpresa], [IdCtaCble]),
    CONSTRAINT [FK_cp_Aprobacion_Ing_Bod_x_OC_det_ct_plancta1] FOREIGN KEY ([IdEmpresa], [IdCtaCble_IVA]) REFERENCES [dbo].[ct_plancta] ([IdEmpresa], [IdCtaCble]),
    CONSTRAINT [FK_cp_Aprobacion_Ing_Bod_x_OC_det_in_Ing_Egr_Inven_det] FOREIGN KEY ([IdEmpresa_Ing_Egr_Inv], [IdSucursal_Ing_Egr_Inv], [IdMovi_inven_tipo_Ing_Egr_Inv], [IdNumMovi_Ing_Egr_Inv], [Secuencia_Ing_Egr_Inv]) REFERENCES [dbo].[in_Ing_Egr_Inven_det] ([IdEmpresa], [IdSucursal], [IdMovi_inven_tipo], [IdNumMovi], [Secuencia]),
    CONSTRAINT [FK_cp_Aprobacion_Ing_Bod_x_OC_det_in_Producto] FOREIGN KEY ([IdEmpresa], [IdProducto]) REFERENCES [dbo].[in_Producto] ([IdEmpresa], [IdProducto]),
    CONSTRAINT [FK_cp_Aprobacion_Ing_Bod_x_OC_det_in_UnidadMedida] FOREIGN KEY ([IdUnidadMedida]) REFERENCES [dbo].[in_UnidadMedida] ([IdUnidadMedida]),
    CONSTRAINT [FK_cp_Aprobacion_Ing_Bod_x_OC_det_tb_sis_Impuesto] FOREIGN KEY ([IdCod_Impuesto_Iva]) REFERENCES [dbo].[tb_sis_Impuesto] ([IdCod_Impuesto])
);

