CREATE TABLE [dbo].[cp_conciliacion_det] (
    [IdEmpresa]        INT           NOT NULL,
    [IdConciliacion]   NUMERIC (18)  NOT NULL,
    [Secuencia]        INT           NOT NULL,
    [IdEmpresa_op]     INT           NULL,
    [IdOrdenPago_op]   NUMERIC (18)  NULL,
    [Secuencia_op]     INT           NULL,
    [IdEmpresa_cxp]    INT           NULL,
    [IdTipoCbte_cxp]   INT           NULL,
    [IdCbteCble_cxp]   NUMERIC (18)  NULL,
    [IdEmpresa_pago]   INT           NOT NULL,
    [IdTipoCbte_pago]  INT           NOT NULL,
    [IdCbteCble_pago]  NUMERIC (18)  NOT NULL,
    [MontoAplicado]    FLOAT (53)    NOT NULL,
    [SaldoAnterior]    FLOAT (53)    NOT NULL,
    [SaldoActual]      FLOAT (53)    NOT NULL,
    [Observacion]      VARCHAR (250) NOT NULL,
    [fechaTransaccion] DATETIME      NOT NULL,
    CONSTRAINT [PK_cp_conciliacion_det] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdConciliacion] ASC, [Secuencia] ASC),
    CONSTRAINT [FK_cp_conciliacion_det_cp_conciliacion] FOREIGN KEY ([IdEmpresa], [IdConciliacion]) REFERENCES [dbo].[cp_conciliacion] ([IdEmpresa], [IdConciliacion]),
    CONSTRAINT [FK_cp_conciliacion_det_cp_orden_pago_det] FOREIGN KEY ([IdEmpresa_op], [IdOrdenPago_op], [Secuencia_op]) REFERENCES [dbo].[cp_orden_pago_det] ([IdEmpresa], [IdOrdenPago], [Secuencia]),
    CONSTRAINT [FK_cp_conciliacion_det_ct_cbtecble] FOREIGN KEY ([IdEmpresa_cxp], [IdTipoCbte_cxp], [IdCbteCble_cxp]) REFERENCES [dbo].[ct_cbtecble] ([IdEmpresa], [IdTipoCbte], [IdCbteCble]),
    CONSTRAINT [FK_cp_conciliacion_det_ct_cbtecble1] FOREIGN KEY ([IdEmpresa_pago], [IdTipoCbte_pago], [IdCbteCble_pago]) REFERENCES [dbo].[ct_cbtecble] ([IdEmpresa], [IdTipoCbte], [IdCbteCble])
);

