CREATE TABLE [dbo].[cxc_liquidacion_comisiones_det] (
    [IdEmpresa]          INT          NOT NULL,
    [IdLiquidacion]      NUMERIC (18) NOT NULL,
    [Secuencia]          INT          NOT NULL,
    [IdVendedor]         INT          NOT NULL,
    [fa_IdEmpresa]       INT          NOT NULL,
    [fa_IdSucursal]      INT          NOT NULL,
    [fa_IdBodega]        INT          NOT NULL,
    [fa_IdCbteVta]       NUMERIC (18) NOT NULL,
    [SubtotalFactura]    FLOAT (53)   NOT NULL,
    [IvaFactura]         FLOAT (53)   NOT NULL,
    [TotalFactura]       FLOAT (53)   NOT NULL,
    [TotalCobrado]       FLOAT (53)   NOT NULL,
    [BaseComision]       FLOAT (53)   NOT NULL,
    [PorcentajeComision] FLOAT (53)   NOT NULL,
    [TotalAComisionar]   FLOAT (53)   NOT NULL,
    [TotalComisionado]   FLOAT (53)   NOT NULL,
    [TotalLiquidacion]   FLOAT (53)   NOT NULL,
    [NoComisiona]        BIT          NOT NULL,
    CONSTRAINT [PK_cxc_liquidacion_comisiones_det] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdLiquidacion] ASC, [Secuencia] ASC),
    CONSTRAINT [FK_cxc_liquidacion_comisiones_det_cxc_liquidacion_comisiones] FOREIGN KEY ([IdEmpresa], [IdLiquidacion]) REFERENCES [dbo].[cxc_liquidacion_comisiones] ([IdEmpresa], [IdLiquidacion]),
    CONSTRAINT [FK_cxc_liquidacion_comisiones_det_fa_factura] FOREIGN KEY ([fa_IdEmpresa], [fa_IdSucursal], [fa_IdBodega], [fa_IdCbteVta]) REFERENCES [dbo].[fa_factura] ([IdEmpresa], [IdSucursal], [IdBodega], [IdCbteVta]),
    CONSTRAINT [FK_cxc_liquidacion_comisiones_det_fa_Vendedor] FOREIGN KEY ([IdEmpresa], [IdVendedor]) REFERENCES [dbo].[fa_Vendedor] ([IdEmpresa], [IdVendedor])
);

