CREATE TABLE [dbo].[cxc_cobro_tipo] (
    [IdCobro_tipo]                VARCHAR (20) NOT NULL,
    [tc_descripcion]              VARCHAR (50) NOT NULL,
    [tc_EsCheque]                 VARCHAR (1)  NOT NULL,
    [tc_Afecha]                   VARCHAR (1)  NOT NULL,
    [tc_interno]                  VARCHAR (1)  NOT NULL,
    [Estado]                      VARCHAR (1)  NOT NULL,
    [tc_generaNCAuto]             VARCHAR (1)  NOT NULL,
    [tc_abreviatura]              CHAR (5)     NOT NULL,
    [tc_cobroDirecto]             VARCHAR (1)  NOT NULL,
    [tc_cobroInDirecto]           VARCHAR (1)  NOT NULL,
    [tc_docXCobrar]               VARCHAR (1)  NOT NULL,
    [tc_Orden]                    INT          NOT NULL,
    [tc_seMuestraManCheque]       VARCHAR (1)  NOT NULL,
    [tc_Que_Tipo_Registro_Genera] VARCHAR (20) NOT NULL,
    [tc_Tomar_Cta_Cble_De]        VARCHAR (20) NULL,
    [tc_seCobra]                  VARCHAR (1)  NOT NULL,
    [IdEstadoCobro_Inicial]       VARCHAR (5)  NULL,
    [ESRetenIVA]                  CHAR (1)     NULL,
    [ESRetenFTE]                  CHAR (1)     NULL,
    [PorcentajeRet]               FLOAT (53)   NULL,
    [IdUsuario]                   VARCHAR (20) NULL,
    [Fecha_Transac]               DATETIME     NULL,
    [IdUsuarioUltMod]             VARCHAR (20) NULL,
    [Fecha_UltMod]                DATETIME     NULL,
    [IdUsuarioUltAnu]             VARCHAR (20) NULL,
    [Fecha_UltAnu]                DATETIME     NULL,
    [nom_pc]                      VARCHAR (50) NULL,
    [ip]                          VARCHAR (50) NULL,
    [tc_SePuede_Depositar]        CHAR (1)     NULL,
    [IdMotivo_tipo_cobro]         VARCHAR (15) NULL,
    CONSTRAINT [PK_cxc_cobro_tipo] PRIMARY KEY CLUSTERED ([IdCobro_tipo] ASC),
    CONSTRAINT [FK_cxc_cobro_tipo_cxc_cobro_tipo_motivo] FOREIGN KEY ([IdMotivo_tipo_cobro]) REFERENCES [dbo].[cxc_cobro_tipo_motivo] ([IdMotivo_tipo_cobro])
);

