CREATE TABLE [dbo].[cxc_cancelacion_Intercompany] (
    [IdEmpresa]          INT           NOT NULL,
    [IdCancelacion]      NUMERIC (18)  NOT NULL,
    [IdCliente]          NUMERIC (18)  NOT NULL,
    [IdCobro_tipo]       VARCHAR (20)  NOT NULL,
    [IdBanco_Deposito]   INT           NULL,
    [Observacion]        VARCHAR (250) NULL,
    [PapeletaDeposito]   VARCHAR (50)  NULL,
    [cbteban_IdEmpresa]  INT           NULL,
    [cbteban_IdCbteCble] NUMERIC (18)  NULL,
    [cbteban_IdTipocbte] INT           NULL,
    [cr_TotalCobro]      FLOAT (53)    NULL,
    [cr_fecha]           DATE          NULL,
    [cr_fechaDocu]       DATE          NULL,
    [cr_fechaCobro]      DATE          NULL,
    [cr_observacion]     VARCHAR (300) NULL,
    [cr_Banco]           VARCHAR (50)  NULL,
    [cr_cuenta]          VARCHAR (100) NULL,
    [cr_NumDocumento]    VARCHAR (100) NULL,
    [cr_Tarjeta]         VARCHAR (50)  NULL,
    [cr_propietarioCta]  VARCHAR (100) NULL,
    [cr_estado]          CHAR (1)      NULL,
    [Fecha_Transac]      DATETIME      NULL,
    [IdUsuario]          VARCHAR (20)  NULL,
    [IdUsuarioUltMod]    VARCHAR (20)  NULL,
    [Fecha_UltMod]       DATETIME      NULL,
    [IdUsuarioUltAnu]    VARCHAR (20)  NULL,
    [Fecha_UltAnu]       DATETIME      NULL,
    [nom_pc]             VARCHAR (50)  NULL,
    [ip]                 VARCHAR (50)  NULL,
    [IdSucursal]         INT           NOT NULL,
    [GeneraDeps]         CHAR (1)      NOT NULL,
    [IdCaja]             INT           NOT NULL,
    [IdTipoNotaCredito]  VARCHAR (3)   NULL,
    CONSTRAINT [PK_cxc_cancelacion_Intercompany] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdCancelacion] ASC),
    CONSTRAINT [FK_cxc_cancelacion_Intercompany_cxc_cobro_tipo] FOREIGN KEY ([IdCobro_tipo]) REFERENCES [dbo].[cxc_cobro_tipo] ([IdCobro_tipo]),
    CONSTRAINT [FK_cxc_cancelacion_Intercompany_fa_cliente] FOREIGN KEY ([IdEmpresa], [IdCliente]) REFERENCES [dbo].[fa_cliente] ([IdEmpresa], [IdCliente])
);

