CREATE TABLE [dbo].[fa_devol_venta] (
    [IdEmpresa]                     INT           NOT NULL,
    [IdSucursal]                    INT           NOT NULL,
    [IdBodega]                      INT           NOT NULL,
    [IdDevolucion]                  NUMERIC (18)  NOT NULL,
    [CodDevolucion]                 VARCHAR (20)  NOT NULL,
    [IdNota]                        NUMERIC (18)  NOT NULL,
    [IdCliente]                     NUMERIC (18)  NOT NULL,
    [IdVendedor]                    INT           NOT NULL,
    [IdCbteVta]                     NUMERIC (18)  NOT NULL,
    [dv_fecha]                      DATETIME      NOT NULL,
    [Estado]                        CHAR (1)      NOT NULL,
    [dv_Observacion]                VARCHAR (300) NOT NULL,
    [dv_seguro]                     FLOAT (53)    NOT NULL,
    [dv_flete]                      FLOAT (53)    NOT NULL,
    [dv_interes]                    FLOAT (53)    NOT NULL,
    [dv_OtroValor1]                 FLOAT (53)    NOT NULL,
    [dv_OtroValor2]                 FLOAT (53)    NOT NULL,
    [IdUsuario]                     CHAR (20)     NULL,
    [MotivoAnulacion]               VARCHAR (50)  NULL,
    [mvInv_IdEmpresa]               INT           NULL,
    [mvInv_IdSucursal]              INT           NULL,
    [mvInv_IdBodega]                INT           NULL,
    [mvInv_IdMovi_inven_tipo]       INT           NULL,
    [mvInv_IdNumMovi]               NUMERIC (18)  NULL,
    [mvInv_IdEmpresa_x_Anu]         INT           NULL,
    [mvInv_IdSucursal_x_Anu]        INT           NULL,
    [mvInv_IdBodega_x_Anu]          INT           NULL,
    [mvInv_IdMovi_inven_tipo_x_Anu] INT           NULL,
    [mvInv_IdNumMovi_x_Anu]         NUMERIC (18)  NULL,
    CONSTRAINT [PK_fa_devol_venta] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdSucursal] ASC, [IdBodega] ASC, [IdDevolucion] ASC),
    CONSTRAINT [FK_fa_devol_venta_fa_cliente] FOREIGN KEY ([IdEmpresa], [IdCliente]) REFERENCES [dbo].[fa_cliente] ([IdEmpresa], [IdCliente]),
    CONSTRAINT [FK_fa_devol_venta_fa_factura] FOREIGN KEY ([IdEmpresa], [IdSucursal], [IdBodega], [IdCbteVta]) REFERENCES [dbo].[fa_factura] ([IdEmpresa], [IdSucursal], [IdBodega], [IdCbteVta]),
    CONSTRAINT [FK_fa_devol_venta_fa_notaCreDeb] FOREIGN KEY ([IdEmpresa], [IdSucursal], [IdBodega], [IdNota]) REFERENCES [dbo].[fa_notaCreDeb] ([IdEmpresa], [IdSucursal], [IdBodega], [IdNota]),
    CONSTRAINT [FK_fa_devol_venta_fa_Vendedor] FOREIGN KEY ([IdEmpresa], [IdVendedor]) REFERENCES [dbo].[fa_Vendedor] ([IdEmpresa], [IdVendedor]),
    CONSTRAINT [FK_fa_devol_venta_in_movi_inve] FOREIGN KEY ([mvInv_IdEmpresa], [mvInv_IdSucursal], [mvInv_IdBodega], [mvInv_IdMovi_inven_tipo], [mvInv_IdNumMovi]) REFERENCES [dbo].[in_movi_inve] ([IdEmpresa], [IdSucursal], [IdBodega], [IdMovi_inven_tipo], [IdNumMovi]),
    CONSTRAINT [FK_fa_devol_venta_in_movi_inve1] FOREIGN KEY ([mvInv_IdEmpresa_x_Anu], [mvInv_IdSucursal_x_Anu], [mvInv_IdBodega_x_Anu], [mvInv_IdMovi_inven_tipo_x_Anu], [mvInv_IdNumMovi_x_Anu]) REFERENCES [dbo].[in_movi_inve] ([IdEmpresa], [IdSucursal], [IdBodega], [IdMovi_inven_tipo], [IdNumMovi]),
    CONSTRAINT [FK_fa_devol_venta_tb_bodega] FOREIGN KEY ([IdEmpresa], [IdSucursal], [IdBodega]) REFERENCES [dbo].[tb_bodega] ([IdEmpresa], [IdSucursal], [IdBodega])
);

