CREATE TABLE [dbo].[FaltanteAntorcha$] (
    [ESTABLECIMIENTO]      NVARCHAR (255) NULL,
    [ID_BODEGA]            NVARCHAR (255) NULL,
    [ID_PRODUCTO_ANTERIOR] NVARCHAR (255) NULL,
    [ID_PRODUCTOACTUAL]    NVARCHAR (255) NULL,
    [UNIDAD]               NVARCHAR (255) NULL,
    [CANTIDAD]             FLOAT (53)     NULL,
    [COSTO_TOTAL]          FLOAT (53)     NULL
);

