CREATE TABLE [dbo].[FaltanteLibreria$] (
    [ESTABLECIMIENTO]     NVARCHAR (255) NULL,
    [ID_BODEGA]           NVARCHAR (255) NULL,
    [ID_PRODUCTOANTERIOR] NVARCHAR (255) NULL,
    [ID_PROCUCTOACTUAL]   NVARCHAR (255) NULL,
    [UNIDAD]              NVARCHAR (255) NULL,
    [CANTIDAD]            FLOAT (53)     NULL,
    [COSTO_TOTAL]         FLOAT (53)     NULL
);

