CREATE TABLE [dbo].[ro_empleado] (
    [IdEmpresa]                            INT             NOT NULL,
    [IdEmpleado]                           NUMERIC (18)    NOT NULL,
    [IdEmpleado_Supervisor]                NUMERIC (18)    NULL,
    [IdPersona]                            NUMERIC (18)    NOT NULL,
    [IdSucursal]                           INT             NOT NULL,
    [IdTipoEmpleado]                       VARCHAR (10)    NOT NULL,
    [em_codigo]                            VARCHAR (50)    NULL,
    [Codigo_Biometrico]                    VARCHAR (50)    NULL,
    [em_lugarNacimiento]                   VARCHAR (50)    NOT NULL,
    [em_CarnetIees]                        VARCHAR (20)    NULL,
    [em_cedulaMil]                         VARCHAR (20)    NULL,
    [em_fecha_ingreso]                     DATETIME        NULL,
    [em_fechaSalida]                       DATETIME        NULL,
    [em_fechaTerminoContra]                DATETIME        NULL,
    [em_fechaIngaRol]                      DATETIME        NULL,
    [em_SeAcreditaBanco]                   VARCHAR (1)     NULL,
    [em_tipoCta]                           VARCHAR (25)    NULL,
    [em_NumCta]                            VARCHAR (20)    NULL,
    [em_SepagaBeneficios]                  VARCHAR (1)     NULL,
    [em_SePagaConTablaSec]                 VARCHAR (1)     NULL,
    [em_estado]                            VARCHAR (1)     NOT NULL,
    [em_sueldoBasicoMen]                   FLOAT (53)      NOT NULL,
    [em_SueldoExtraMen]                    FLOAT (53)      NULL,
    [em_MovilizacionQuincenal]             FLOAT (53)      NULL,
    [em_foto]                              IMAGE           NULL,
    [em_empEspecial]                       VARCHAR (1)     NULL,
    [em_pagoFdoRsv]                        VARCHAR (1)     NULL,
    [em_huella]                            VARCHAR (4000)  NULL,
    [IdCodSectorial]                       INT             NULL,
    [IdDepartamento]                       INT             NOT NULL,
    [IdTipoSangre]                         VARCHAR (10)    NULL,
    [IdCargo]                              INT             NULL,
    [IdCtaCble_Emplea]                     VARCHAR (20)    NULL,
    [IdCiudad]                             VARCHAR (25)    NULL,
    [em_mail]                              VARCHAR (50)    NULL,
    [IdTipoLicencia]                       VARCHAR (10)    NULL,
    [IdCentroCosto]                        VARCHAR (20)    NULL,
    [IdBanco]                              VARCHAR (10)    NULL,
    [Archivo]                              VARBINARY (MAX) NULL,
    [NombreArchivo]                        VARCHAR (200)   NULL,
    [IdArea]                               INT             NULL,
    [IdDivision]                           INT             NULL,
    [IdCentroCosto_sub_centro_costo]       VARCHAR (20)    NULL,
    [IdUsuario]                            VARCHAR (20)    NULL,
    [Fecha_Transaccion]                    DATETIME        NULL,
    [IdUsuarioUltModi]                     VARCHAR (20)    NULL,
    [Fecha_UltMod]                         DATETIME        NULL,
    [IdUsuarioUltAnu]                      VARCHAR (20)    NULL,
    [Fecha_UltAnu]                         DATETIME        NULL,
    [MotivoAnulacion]                      VARCHAR (100)   NULL,
    [nom_pc]                               VARCHAR (25)    NULL,
    [ip]                                   VARCHAR (25)    NULL,
    [por_discapacidad]                     FLOAT (53)      NOT NULL,
    [carnet_conadis]                       VARCHAR (50)    NULL,
    [recibi_uniforme]                      CHAR (1)        NULL,
    [talla_pant]                           FLOAT (53)      NULL,
    [talla_camisa]                         VARCHAR (50)    NULL,
    [talla_zapato]                         FLOAT (53)      NULL,
    [em_status]                            VARCHAR (10)    NULL,
    [IdCondicionDiscapacidadSRI]           VARCHAR (10)    NULL,
    [IdTipoIdentDiscapacitadoSustitutoSRI] VARCHAR (10)    NULL,
    [IdentDiscapacitadoSustitutoSRI]       VARCHAR (50)    NULL,
    [IdAplicaConvenioDobleImposicionSRI]   VARCHAR (10)    NULL,
    [IdTipoResidenciaSRI]                  VARCHAR (10)    NULL,
    [IdTipoSistemaSalarioNetoSRI]          VARCHAR (10)    NULL,
    [es_AcreditaHorasExtras]               BIT             NOT NULL,
    [IdTipoAnticipo]                       VARCHAR (10)    NULL,
    [ValorAnticipo]                        FLOAT (53)      NULL,
    [CodigoSectorial]                      VARCHAR (25)    NULL,
    [es_TruncarDecimalAnticipo]            BIT             NULL,
    [em_AnticipoSueldo]                    FLOAT (53)      NULL,
    [IdBanco_Acreditacion]                 INT             NULL,
    [IdGrupo]                              INT             NULL,
    [Marca_Biometrico]                     BIT             NOT NULL,
    [em_motivo_salisa]                     VARCHAR (500)   NULL,
    [IdHorario]                            INT             NULL,
    [IdPuntoCargo]                         INT             NULL,
    CONSTRAINT [PK_ro_empleado] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdEmpleado] ASC),
    CONSTRAINT [FK_ro_empleado_ct_plancta] FOREIGN KEY ([IdEmpresa], [IdCtaCble_Emplea]) REFERENCES [dbo].[ct_plancta] ([IdEmpresa], [IdCtaCble]),
    CONSTRAINT [FK_ro_empleado_ro_Cargo] FOREIGN KEY ([IdEmpresa], [IdCargo]) REFERENCES [dbo].[ro_cargo] ([IdEmpresa], [IdCargo]),
    CONSTRAINT [FK_ro_empleado_ro_Catalogo] FOREIGN KEY ([IdTipoEmpleado]) REFERENCES [dbo].[ro_catalogo] ([CodCatalogo]),
    CONSTRAINT [FK_ro_empleado_ro_Catalogo1] FOREIGN KEY ([IdTipoSangre]) REFERENCES [dbo].[ro_catalogo] ([CodCatalogo]),
    CONSTRAINT [FK_ro_empleado_ro_Catalogo2] FOREIGN KEY ([IdTipoLicencia]) REFERENCES [dbo].[ro_catalogo] ([CodCatalogo]),
    CONSTRAINT [FK_ro_empleado_ro_Catalogo3] FOREIGN KEY ([IdTipoLicencia]) REFERENCES [dbo].[ro_catalogo] ([CodCatalogo]),
    CONSTRAINT [FK_ro_empleado_ro_Departamento] FOREIGN KEY ([IdEmpresa], [IdDepartamento]) REFERENCES [dbo].[ro_Departamento] ([IdEmpresa], [IdDepartamento]),
    CONSTRAINT [FK_ro_empleado_ro_Division] FOREIGN KEY ([IdEmpresa], [IdDivision]) REFERENCES [dbo].[ro_Division] ([IdEmpresa], [IdDivision]),
    CONSTRAINT [FK_ro_empleado_ro_empleado] FOREIGN KEY ([IdEmpresa], [IdEmpleado_Supervisor]) REFERENCES [dbo].[ro_empleado] ([IdEmpresa], [IdEmpleado]),
    CONSTRAINT [FK_ro_empleado_tb_ciudad] FOREIGN KEY ([IdCiudad]) REFERENCES [dbo].[tb_ciudad] ([IdCiudad]),
    CONSTRAINT [FK_ro_empleado_tb_persona] FOREIGN KEY ([IdPersona]) REFERENCES [dbo].[tb_persona] ([IdPersona]),
    CONSTRAINT [FK_ro_empleado_tb_sucursal] FOREIGN KEY ([IdEmpresa], [IdSucursal]) REFERENCES [dbo].[tb_sucursal] ([IdEmpresa], [IdSucursal])
);

