CREATE TABLE [dbo].[tbCONTA_Rpt012] (
    [IdEmpresa]        INT          NOT NULL,
    [IdCtaCble]        VARCHAR (50) NOT NULL,
    [IdPeriodo_0]      INT          NOT NULL,
    [nom_Periodo_0]    VARCHAR (50) NOT NULL,
    [Saldo_Periodo_0]  FLOAT (53)   NOT NULL,
    [IdPeriodo_1]      INT          NOT NULL,
    [nom_Periodo_1]    VARCHAR (50) NOT NULL,
    [Saldo_Periodo_1]  FLOAT (53)   NOT NULL,
    [IdPeriodo_2]      INT          NOT NULL,
    [nom_Periodo_2]    VARCHAR (50) NOT NULL,
    [Saldo_Periodo_2]  FLOAT (53)   NOT NULL,
    [IdPeriodo_3]      INT          NOT NULL,
    [nom_Periodo_3]    VARCHAR (50) NOT NULL,
    [Saldo_Periodo_3]  FLOAT (53)   NOT NULL,
    [IdPeriodo_4]      INT          NOT NULL,
    [nom_Periodo_4]    VARCHAR (50) NOT NULL,
    [Saldo_Periodo_4]  FLOAT (53)   NOT NULL,
    [IdPeriodo_5]      INT          NOT NULL,
    [nom_Periodo_5]    VARCHAR (50) NOT NULL,
    [Saldo_Periodo_5]  FLOAT (53)   NOT NULL,
    [IdPeriodo_6]      INT          NOT NULL,
    [nom_Periodo_6]    VARCHAR (50) NOT NULL,
    [Saldo_Periodo_6]  FLOAT (53)   NOT NULL,
    [IdPeriodo_7]      INT          NOT NULL,
    [nom_Periodo_7]    VARCHAR (50) NOT NULL,
    [Saldo_Periodo_7]  FLOAT (53)   NOT NULL,
    [IdPeriodo_8]      INT          NOT NULL,
    [nom_Periodo_8]    VARCHAR (50) NOT NULL,
    [Saldo_Periodo_8]  FLOAT (53)   NOT NULL,
    [IdPeriodo_9]      INT          NOT NULL,
    [nom_Periodo_9]    VARCHAR (50) NOT NULL,
    [Saldo_Periodo_9]  FLOAT (53)   NOT NULL,
    [IdPeriodo_10]     INT          NOT NULL,
    [nom_Periodo_10]   VARCHAR (50) NOT NULL,
    [Saldo_Periodo_10] FLOAT (53)   NOT NULL,
    [IdPeriodo_11]     INT          NOT NULL,
    [nom_Periodo_11]   VARCHAR (50) NOT NULL,
    [Saldo_Periodo_11] FLOAT (53)   NOT NULL,
    [IdPeriodo_12]     INT          NOT NULL,
    [nom_Periodo_12]   VARCHAR (50) NOT NULL,
    [Saldo_Periodo_12] FLOAT (53)   NOT NULL,
    CONSTRAINT [PK_tbCONTA_Rpt012] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdCtaCble] ASC)
);

