CREATE TABLE [dbo].[tbCXP_Rpt002] (
    [IdEmpresa]           INT            NOT NULL,
    [secuencia]           NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [IdUsuario]           VARCHAR (20)   NULL,
    [Fecha_Transac]       DATETIME       NULL,
    [nom_pc]              VARCHAR (50)   NULL,
    [IdOrden_giro_Tipo]   VARCHAR (6)    NULL,
    [IdCbteCble_Ogiro]    NUMERIC (18)   NULL,
    [co_serie]            VARCHAR (10)   NULL,
    [co_factura]          VARCHAR (50)   NULL,
    [co_FechaFactura]     DATETIME       NULL,
    [co_FechaFactura_vct] DATETIME       NULL,
    [co_plazo]            INT            NULL,
    [xvencer]             FLOAT (53)     NULL,
    [1-30]                FLOAT (53)     NULL,
    [31-60]               FLOAT (53)     NULL,
    [61-90]               FLOAT (53)     NULL,
    [>90]                 FLOAT (53)     NULL,
    [total]               FLOAT (53)     NULL,
    [saldo]               FLOAT (53)     NULL,
    [detalle]             VARCHAR (1000) NULL,
    [NomProveedor]        VARCHAR (500)  NULL,
    [IdProveedor]         DECIMAL (18)   NULL,
    CONSTRAINT [PK_tbCXP_Rpt002] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [secuencia] ASC)
);

