CREATE TABLE [dbo].[tbFa_Rpt_EstadoCta_x_cliente_TAL] (
    [IdRegistro]           NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [IdEmpresa]            INT          NOT NULL,
    [IdSucursal]           INT          NOT NULL,
    [IdBodega]             INT          NOT NULL,
    [Tipo_Trans]           VARCHAR (20) NOT NULL,
    [IdCobro]              NUMERIC (18) NULL,
    [IdCobro_Tipo]         VARCHAR (20) NULL,
    [IdEstadoCobro]        VARCHAR (5)  NULL,
    [Secuencia]            INT          NOT NULL,
    [IdCbte_vta_nt]        NUMERIC (18) NOT NULL,
    [Fecha]                DATE         NOT NULL,
    [Fecha_vto]            DATE         NOT NULL,
    [Dias_Plazo]           INT          NOT NULL,
    [Referencia]           VARCHAR (50) NOT NULL,
    [IdCliente]            NUMERIC (18) NOT NULL,
    [IdEstado_Vencimiento] VARCHAR (50) NULL,
    [Subtotal]             MONEY        NOT NULL,
    [Iva]                  MONEY        NOT NULL,
    [Total]                MONEY        NOT NULL,
    [Saldo]                MONEY        NULL,
    [Usuario]              VARCHAR (20) NOT NULL,
    [PC]                   VARCHAR (50) NOT NULL,
    [Nom_Empresa]          VARCHAR (50) NULL,
    [Nom_Sucursal]         VARCHAR (50) NULL,
    [Nom_Cliente]          VARCHAR (50) NULL,
    [Fecha_Corte]          DATE         NULL,
    [Dias_Vencidos]        INT          NULL,
    [Valor_Vencido]        MONEY        NULL,
    [Valor_x_vencer]       MONEY        NULL,
    CONSTRAINT [PK_tbRpt_] PRIMARY KEY CLUSTERED ([IdRegistro] ASC)
);

