CREATE TABLE [dbo].[tbMG_in_Producto] (
    [IdEmpresa]            INT             NOT NULL,
    [IdProducto]           NUMERIC (10)    NOT NULL,
    [pr_codigo]            NVARCHAR (40)   NOT NULL,
    [pr_codigo_barra]      NVARCHAR (25)   NOT NULL,
    [IdProductoTipo]       INT             NOT NULL,
    [IdPresentacion]       VARCHAR (5)     NOT NULL,
    [IdCategoria]          VARCHAR (25)    NOT NULL,
    [pr_descripcion]       NVARCHAR (500)  NOT NULL,
    [pr_observacion]       NVARCHAR (1000) NOT NULL,
    [IdUnidadMedida]       VARCHAR (25)    NOT NULL,
    [pr_precio_publico]    FLOAT (53)      NOT NULL,
    [pr_precio_mayor]      FLOAT (53)      NOT NULL,
    [pr_precio_minimo]     FLOAT (53)      NOT NULL,
    [pr_precio_puerta]     FLOAT (53)      NOT NULL,
    [pr_stock]             FLOAT (53)      NOT NULL,
    [pr_pedidos]           FLOAT (53)      NOT NULL,
    [pr_ManejaIva]         CHAR (10)       NOT NULL,
    [pr_ManejaSeries]      CHAR (10)       NOT NULL,
    [pr_costo_fob]         FLOAT (53)      NOT NULL,
    [pr_costo_CIF]         FLOAT (53)      NOT NULL,
    [pr_costo_promedio]    FLOAT (53)      NOT NULL,
    [IdCtaCble_Inven]      VARCHAR (20)    NULL,
    [IdCtaCble_Vta]        VARCHAR (20)    NULL,
    [IdCtaCble_CosBaseIva] VARCHAR (20)    NULL,
    [IdCtaCble_CosBase0]   VARCHAR (20)    NULL,
    [IdCtaCble_VenIva]     VARCHAR (20)    NULL,
    [IdCtaCble_Ven0]       VARCHAR (20)    NULL,
    [IdCtaCble_DesIva]     VARCHAR (20)    NULL,
    [IdCtaCble_Des0]       VARCHAR (20)    NULL,
    [IdCtaCble_DevIva]     VARCHAR (20)    NULL,
    [IdCtaCble_Dev0]       VARCHAR (20)    NULL,
    [IdProveedor]          NUMERIC (18)    NOT NULL,
    [IdMarca]              INT             NOT NULL,
    [pr_DiasMaritimo]      INT             NOT NULL,
    [pr_DiasAereo]         INT             NOT NULL,
    [pr_DiasTerrestre]     INT             NOT NULL,
    [pr_largo]             FLOAT (53)      NOT NULL,
    [pr_alto]              FLOAT (53)      NOT NULL,
    [pr_profundidad]       FLOAT (53)      NOT NULL,
    [pr_peso]              FLOAT (53)      NOT NULL,
    [pr_EstaPromocion]     CHAR (1)        NOT NULL,
    [pr_imagenPeque]       IMAGE           NULL,
    [pr_imagen_Grande]     IMAGE           NULL,
    [pr_partidaArancel]    VARCHAR (15)    NOT NULL,
    [pr_porcentajeArancel] MONEY           NOT NULL,
    [pr_Por_descuento]     FLOAT (53)      NOT NULL,
    [pr_stock_maximo]      FLOAT (53)      NOT NULL,
    [pr_stock_minimo]      FLOAT (53)      NOT NULL,
    [IdUsuario]            NVARCHAR (20)   NOT NULL,
    [Fecha_Transac]        DATETIME        NOT NULL,
    [IdUsuarioUltMod]      NVARCHAR (20)   NOT NULL,
    [Fecha_UltMod]         DATETIME        NOT NULL,
    [IdUsuarioUltAnu]      NVARCHAR (20)   NULL,
    [Fecha_UltAnu]         DATETIME        NULL,
    [pr_motivoAnulacion]   NVARCHAR (50)   NULL,
    [nom_pc]               NVARCHAR (50)   NOT NULL,
    [ip]                   NVARCHAR (25)   NOT NULL,
    [Estado]               CHAR (1)        NOT NULL
);

