CREATE TABLE [dbo].[tbMG_Talme_Empleado] (
    [Rolemp_codigo]           FLOAT (53)     NULL,
    [Rolemp_nombre]           NVARCHAR (255) NULL,
    [Rolemp_cedula]           NVARCHAR (255) NULL,
    [Rolemp_fec_nac]          DATETIME       NULL,
    [Rolemp_lugar]            NVARCHAR (255) NULL,
    [Rolemp_direccion]        NVARCHAR (255) NULL,
    [Rolemp_telefono]         NVARCHAR (255) NULL,
    [Rolemp_fec_ing]          DATETIME       NULL,
    [Rolemp_division]         NVARCHAR (255) NULL,
    [Rolemp_departamento]     NVARCHAR (255) NULL,
    [Rolemp_cargo]            NVARCHAR (255) NULL,
    [Rolemp_numero_iess]      NVARCHAR (255) NULL,
    [Rolemp_Sueldo_mes]       FLOAT (53)     NULL,
    [Rolemp_Sueldo_Quincena]  FLOAT (53)     NULL,
    [Rolemp_fec_salida]       DATETIME       NULL,
    [Rolemp_estado_civil]     NVARCHAR (255) NULL,
    [Rolemp_sexo]             FLOAT (53)     NULL,
    [Rolemp_Anticipos_sueldo] FLOAT (53)     NULL,
    [Rolemp_tpo_cta]          NVARCHAR (255) NULL,
    [Rolemp_cuenta_banco]     NVARCHAR (255) NULL,
    [Rolemp_dias_acum]        FLOAT (53)     NULL,
    [Rolemp_valor_acum]       FLOAT (53)     NULL,
    [Rolemp_aporte_iess]      BIT            NOT NULL,
    [Rolemp_status]           NVARCHAR (255) NULL,
    [Rolemp_maternidad]       BIT            NOT NULL,
    [Rolemp_vac_ini]          DATETIME       NULL,
    [Rolemp_vac_fin]          DATETIME       NULL,
    [Rolemp_vac_vlr]          FLOAT (53)     NULL,
    [Rolemp_libmil]           NVARCHAR (255) NULL,
    [Rolemp_ant_acum]         FLOAT (53)     NULL,
    [Rolemp_cuenta]           NVARCHAR (255) NULL,
    [Rolemp_usuario]          NVARCHAR (255) NULL,
    [Rolemp_fecha]            DATETIME       NULL,
    [Rolemp_sectorial]        NVARCHAR (255) NULL,
    [Rolemp_costo]            NVARCHAR (255) NULL,
    [Rolemp_nacion]           NVARCHAR (255) NULL,
    [Rolemp_benley]           BIT            NOT NULL,
    [Rolemp_region]           NVARCHAR (255) NULL,
    [Rolemp_cat]              NVARCHAR (255) NULL,
    [Rolemp_otro]             FLOAT (53)     NULL,
    [Rolemp_CtaDebito]        NVARCHAR (255) NULL,
    [Rolemp_CtaContableEmpl]  NVARCHAR (255) NULL,
    [Rolemp_PagarFRMensual]   BIT            NOT NULL,
    [Rolemp_fechaCalcularVac] DATETIME       NULL,
    [Rolemp_sucursal]         NVARCHAR (255) NULL
);

