CREATE TABLE [dbo].[tbMG_Productos_Tal] (
    [Inv_codigo]              NVARCHAR (20)  NOT NULL,
    [Inv_nombre]              NVARCHAR (50)  NULL,
    [Inv_descripcion]         NVARCHAR (150) NULL,
    [Inv_tipo]                NVARCHAR (3)   NULL,
    [Inv_categoria]           NVARCHAR (3)   NULL,
    [Inv_linea]               NVARCHAR (3)   NULL,
    [Inv_medida]              NVARCHAR (10)  NULL,
    [Inv_peso]                FLOAT (53)     NULL,
    [Inv_disponible_inicial]  FLOAT (53)     NULL,
    [Inv_fraccion]            FLOAT (53)     NULL,
    [Inv_disponible_anterior] FLOAT (53)     NULL,
    [Inv_disponible]          FLOAT (53)     NULL,
    [Inv_transito]            FLOAT (53)     NULL,
    [Inv_promedio_inicial]    FLOAT (53)     NULL,
    [Inv_promedio_anterior]   FLOAT (53)     NULL,
    [Inv_promedio]            FLOAT (53)     NULL,
    [Inv_ultimo_costo]        FLOAT (53)     NULL,
    [Inv_ultima_compra]       DATETIME       NULL,
    [Inv_ultima_venta]        DATETIME       NULL,
    [Inv_maximo]              FLOAT (53)     NULL,
    [Inv_minimo]              FLOAT (53)     NULL,
    [Inv_iva]                 NVARCHAR (1)   NULL,
    [Inv_precio1]             FLOAT (53)     NULL,
    [Inv_precio2]             FLOAT (53)     NULL,
    [Inv_precio3]             FLOAT (53)     NULL,
    [Inv_precio4]             FLOAT (53)     NULL,
    [Inv_ultima_cotizacion]   FLOAT (53)     NULL,
    [Inv_proveedor]           NVARCHAR (15)  NULL,
    [Inv_FechUltMov]          DATETIME       NULL,
    [Inv_UndXc]               SMALLINT       NULL,
    [Inv_Bonifi]              NVARCHAR (1)   NULL,
    [Inv_Complemento]         BIT            NOT NULL,
    [Inv_Cuenta]              NVARCHAR (15)  NULL,
    [Inv_CostoProductoXTn]    FLOAT (53)     NULL,
    [Inv_Cuenta2]             NVARCHAR (15)  NULL,
    [Inv_Largo]               FLOAT (53)     NULL,
    [Inv_Ancho]               FLOAT (53)     NULL,
    [Inv_PesoEspecifico]      FLOAT (53)     NULL,
    [Inv_Lote]                NVARCHAR (50)  NULL
);

