CREATE TABLE [dbo].[tbPRO_CUS_CID_Rpt005] (
    [IdEmpresa]          INT             NOT NULL,
    [IdUsuario]          VARCHAR (20)    NOT NULL,
    [IdDespacho]         NUMERIC (18)    NOT NULL,
    [Fecha_Transac]      DATETIME        NULL,
    [nom_pc]             VARCHAR (50)    NULL,
    [empresa]            NVARCHAR (50)   NULL,
    [cliente]            NVARCHAR (100)  NULL,
    [pe_cedulaRuc]       VARCHAR (50)    NULL,
    [IdUnidadMedida]     VARCHAR (5)     NULL,
    [FechaReg]           DATE            NULL,
    [FechaIniTras]       DATE            NULL,
    [FechaFinTras]       DATE            NULL,
    [PuntoPartida]       VARCHAR (200)   NULL,
    [PuntoLLegada]       VARCHAR (200)   NULL,
    [Placa]              VARCHAR (20)    NULL,
    [Chofer]             VARCHAR (60)    NULL,
    [TipoTransporte]     VARCHAR (20)    NULL,
    [producto]           NVARCHAR (500)  NULL,
    [CodigoBarraMaestro] NVARCHAR (100)  NULL,
    [cantidad]           FLOAT (53)      NULL,
    [pesoxcant]          FLOAT (53)      NULL,
    [peso]               DECIMAL (18, 2) NULL,
    [precio]             DECIMAL (18, 2) NULL,
    [ot]                 VARCHAR (20)    NULL,
    [det_observacion]    VARCHAR (200)   NULL,
    [obra]               VARCHAR (100)   NULL,
    [NumDespacho]        VARCHAR (20)    NULL,
    [NumFactura]         VARCHAR (50)    NULL,
    [NumGuia]            VARCHAR (50)    NULL,
    [Su_Descripcion]     NCHAR (60)      NULL,
    [bo_Descripcion]     NCHAR (100)     NULL
);

