CREATE TABLE [dbo].[tbProd_Rpt_PRD_CUS_TAL_002] (
    [IdEmpresa]               INT            NOT NULL,
    [IdGestionProductiva]     DECIMAL (18)   NOT NULL,
    [IdProducto_MateriaPrima] DECIMAL (18)   NULL,
    [IdModeloProd]            INT            NULL,
    [Fecha]                   DATE           NULL,
    [HrsTurno]                VARCHAR (5)    NULL,
    [Tprep]                   VARCHAR (5)    NULL,
    [Despacho]                VARCHAR (5)    NULL,
    [Factor]                  FLOAT (53)     NULL,
    [Num_Personas]            INT            NULL,
    [Consumo]                 FLOAT (53)     NULL,
    [Chatarra]                FLOAT (53)     NULL,
    [Producto]                NVARCHAR (500) NOT NULL,
    [ProductoDeSegunda]       NVARCHAR (500) NOT NULL,
    [Prod_IdProducto]         NUMERIC (18)   NULL,
    [Prod_Largo]              FLOAT (53)     NULL,
    [Prod_Ancho]              FLOAT (53)     NULL,
    [Prod_PsoEsp]             FLOAT (53)     NULL,
    [Prod_Espesor]            FLOAT (53)     NULL,
    [Prod_PsoUnd]             FLOAT (53)     NULL,
    [Prducc_Unidades]         FLOAT (53)     NULL,
    [Prducc_Kg]               FLOAT (53)     NULL,
    [Segunda_IdProducto]      NUMERIC (18)   NULL,
    [Segunda_Unidades]        FLOAT (53)     NULL,
    [Segunda_Kg]              FLOAT (53)     NULL,
    [Chatarra_Kg]             FLOAT (53)     NULL,
    [Peso]                    FLOAT (53)     NULL,
    [Kg_Desp]                 FLOAT (53)     NULL,
    [Rend_Metalico]           FLOAT (53)     NULL,
    [KW]                      FLOAT (53)     NULL,
    [Tiempo_Preparacion]      VARCHAR (5)    NULL,
    [Tiempo_Produccion]       VARCHAR (5)    NULL,
    [Tiempo_Total]            VARCHAR (5)    NULL,
    [Parada_Mecanica]         VARCHAR (5)    NULL,
    [Parada_Electrico]        VARCHAR (5)    NULL,
    [Parada_Logistica]        VARCHAR (5)    NULL,
    [Parada_Otros]            VARCHAR (5)    NULL,
    [TotalParos]              VARCHAR (5)    NULL,
    [Indicadores_TnHrs]       FLOAT (53)     NULL,
    [Indicadores_TimeParda]   FLOAT (53)     NULL,
    [Indicadores_UndsHrs]     FLOAT (53)     NULL,
    [Indicadores_Calidad]     FLOAT (53)     NULL,
    [ModeloProduccion]        VARCHAR (50)   NULL,
    [MateriaPrima]            NVARCHAR (500) NOT NULL,
    [Turno]                   NVARCHAR (50)  NULL,
    [IdUsuario]               VARCHAR (20)   NULL,
    [nom_pc]                  VARCHAR (50)   NULL,
    [Estado]                  CHAR (1)       NULL
);

