CREATE TABLE [dbo].[tbPRO_CUS_CID_Rpt008] (
    [IdEmpresa]               INT             NULL,
    [IdUsuario]               VARCHAR (20)    NULL,
    [Fecha_Transac]           DATETIME        NULL,
    [nom_pc]                  VARCHAR (50)    NULL,
    [CodigoBarra]             NVARCHAR (100)  NULL,
    [dm_observacion]          NVARCHAR (1000) NULL,
    [IdSucursal]              INT             NULL,
    [IdBodega]                INT             NULL,
    [IdMovi_inven_tipo]       INT             NULL,
    [IdNumMovi]               NUMERIC (18)    NULL,
    [Secuencia]               INT             NULL,
    [cb_secuencia]            INT             NULL,
    [IdProducto]              NUMERIC (18)    NULL,
    [cm_fecha]                DATE            NULL,
    [dm_cantidad]             FLOAT (53)      NULL,
    [cm_observacion]          NVARCHAR (1000) NULL,
    [Su_Descripcion]          NCHAR (60)      NULL,
    [bo_Descripcion]          NCHAR (100)     NULL,
    [tm_descripcion]          NVARCHAR (50)   NULL,
    [pr_descripcion]          NVARCHAR (500)  NULL,
    [Id]                      INT             NOT NULL,
    [pr_nombre]               VARCHAR (100)   NOT NULL,
    [NumDocumentoRelacionado] VARCHAR (25)    NOT NULL,
    [NumFactura]              VARCHAR (25)    NOT NULL,
    [oc_NumDocumento]         VARCHAR (20)    NOT NULL,
    [IdOrdenCompra]           NUMERIC (18)    NULL,
    [oc_fecha]                DATE            NULL,
    [oc_observacion]          VARCHAR (1000)  NULL,
    [ocdet_cantidad]          FLOAT (53)      NULL
);

