CREATE TABLE [dbo].[tbPRO_CUS_CID_Rpt006] (
    [IdUsuario]         VARCHAR (20)    NOT NULL,
    [Fecha_Transac]     DATETIME        NULL,
    [nom_pc]            VARCHAR (50)    NOT NULL,
    [CodigoBarra]       NVARCHAR (100)  NULL,
    [dm_observacion]    NVARCHAR (1000) NULL,
    [IdEmpresa]         INT             NOT NULL,
    [IdSucursal]        INT             NULL,
    [IdBodega]          INT             NULL,
    [IdMovi_inven_tipo] INT             NULL,
    [IdNumMovi]         NUMERIC (18)    NULL,
    [Secuencia]         INT             NULL,
    [cb_secuencia]      INT             NULL,
    [IdProducto]        NUMERIC (18)    NULL,
    [cm_fecha]          DATE            NULL,
    [dm_cantidad]       FLOAT (53)      NULL,
    [cm_observacion]    NVARCHAR (1000) NULL,
    [Su_Descripcion]    NCHAR (60)      NULL,
    [bo_Descripcion]    NCHAR (100)     NULL,
    [tm_descripcion]    NVARCHAR (50)   NULL,
    [pr_descripcion]    NVARCHAR (500)  NULL,
    [Id]                INT             NOT NULL,
    CONSTRAINT [PK_tbPRO_CUS_CID_Rpt006_1] PRIMARY KEY CLUSTERED ([IdUsuario] ASC, [nom_pc] ASC, [Id] ASC)
);

