CREATE TABLE [dbo].[tbROL_Rpt003] (
    [IdEmpresa]          INT           NOT NULL,
    [IdPrestamo]         NUMERIC (18)  NOT NULL,
    [IdNomina_Tipo]      INT           NOT NULL,
    [nomi_descripcion]   VARCHAR (50)  NULL,
    [IdEmpleado]         NUMERIC (18)  NOT NULL,
    [pe_nombre]          VARCHAR (100) NOT NULL,
    [pe_apellido]        VARCHAR (100) NOT NULL,
    [IdRubro]            VARCHAR (10)  NOT NULL,
    [ru_descripcion]     VARCHAR (50)  NULL,
    [IdEmpleado_Aprueba] NUMERIC (18)  NOT NULL,
    [pe_nombre_apru]     VARCHAR (100) NOT NULL,
    [pe_apellido_apru]   VARCHAR (100) NOT NULL,
    [codigo]             VARCHAR (10)  NOT NULL,
    [ca_descripcion]     VARCHAR (250) NULL,
    [estado]             CHAR (1)      NOT NULL,
    [Fecha]              DATETIME      NOT NULL,
    [MontoSol]           FLOAT (53)    NULL,
    [TasaInteres]        FLOAT (53)    NULL,
    [NumCuotas]          INT           NOT NULL,
    [cod_pago]           VARCHAR (10)  NOT NULL,
    [peri_pago]          VARCHAR (250) NULL,
    [Fecha_PriPago]      DATETIME      NOT NULL,
    [Observacion]        VARCHAR (250) NULL,
    [TotalPrestado]      FLOAT (53)    NULL,
    [TotalCobrado]       FLOAT (53)    NULL,
    [SaldoPrestado]      FLOAT (53)    NULL,
    [NumCuotaDet]        INT           NOT NULL,
    [SaldoInicial]       FLOAT (53)    NULL,
    [Interes]            FLOAT (53)    NULL,
    [AbonoCapital]       FLOAT (53)    NULL,
    [TotalCuota]         FLOAT (53)    NULL,
    [Saldo]              FLOAT (53)    NULL,
    [FechaPago]          DATETIME      NOT NULL,
    [EstadoPago]         VARCHAR (10)  NOT NULL,
    [Observacion_det]    VARCHAR (250) NULL,
    [Estado_Det]         CHAR (1)      NOT NULL,
    [Fecha_Transac]      DATETIME      NOT NULL,
    [IdUsuario]          VARCHAR (50)  NOT NULL,
    [nom_pc]             VARCHAR (50)  NOT NULL
);

