CREATE TABLE [dbo].[tbROL_NominaGeneral] (
    [IdEmpresa]          INT           NOT NULL,
    [IdEmpleado]         NUMERIC (18)  NOT NULL,
    [IdNomina_Tipo]      INT           NOT NULL,
    [IdNomina_TipoLiqui] INT           NOT NULL,
    [IdPeriodo]          INT           NOT NULL,
    [nom_pc]             VARCHAR (50)  NOT NULL,
    [IdUsuario]          VARCHAR (50)  NOT NULL,
    [NomEmpleado]        VARCHAR (200) NOT NULL,
    [IdDivision]         INT           NOT NULL,
    [NomDivision]        VARCHAR (100) NOT NULL,
    [IdDepartamento]     INT           NOT NULL,
    [NomDepartamento]    VARCHAR (100) NOT NULL,
    [IdRubroIng1]        VARCHAR (10)  NULL,
    [NRubroIng1]         VARCHAR (10)  NULL,
    [ValorIng1]          FLOAT (53)    NULL,
    [IdRubroIng2]        VARCHAR (10)  NULL,
    [NRubroIng2]         VARCHAR (10)  NULL,
    [ValorIng2]          FLOAT (53)    NULL,
    [IdRubroIng3]        VARCHAR (10)  NULL,
    [NRubroIng3]         VARCHAR (10)  NULL,
    [ValorIng3]          FLOAT (53)    NULL,
    [IdRubroIng4]        VARCHAR (10)  NULL,
    [NRubroIng4]         VARCHAR (10)  NULL,
    [ValorIng4]          FLOAT (53)    NULL,
    [IdRubroIng5]        VARCHAR (10)  NULL,
    [NRubroIng5]         VARCHAR (10)  NULL,
    [ValorIng5]          FLOAT (53)    NULL,
    [IdRubroIng6]        VARCHAR (10)  NULL,
    [NRubroIng6]         VARCHAR (10)  NULL,
    [ValorIng6]          FLOAT (53)    NULL,
    [IdRubroIng7]        VARCHAR (10)  NULL,
    [NRubroIng7]         VARCHAR (10)  NULL,
    [ValorIng7]          FLOAT (53)    NULL,
    [IdRubroIng8]        VARCHAR (10)  NULL,
    [NRubroIng8]         VARCHAR (10)  NULL,
    [ValorIng8]          FLOAT (53)    NULL,
    [IdRubroIng9]        VARCHAR (10)  NULL,
    [NRubroIng9]         VARCHAR (10)  NULL,
    [ValorIng9]          FLOAT (53)    NULL,
    [IdRubroIng10]       VARCHAR (10)  NULL,
    [NRubroIng10]        VARCHAR (10)  NULL,
    [ValorIng10]         FLOAT (53)    NULL,
    [TotalIng]           FLOAT (53)    NULL,
    [IdRubroEgr1]        VARCHAR (10)  NULL,
    [NRubroEgr1]         VARCHAR (10)  NULL,
    [ValorEgr1]          FLOAT (53)    NULL,
    [IdRubroEgr2]        VARCHAR (10)  NULL,
    [NRubroEgr2]         VARCHAR (10)  NULL,
    [ValorEgr2]          FLOAT (53)    NULL,
    [IdRubroEgr3]        VARCHAR (10)  NULL,
    [NRubroEgr3]         VARCHAR (10)  NULL,
    [ValorEgr3]          FLOAT (53)    NULL,
    [IdRubroEgr4]        VARCHAR (10)  NULL,
    [NRubroEgr4]         VARCHAR (10)  NULL,
    [ValorEgr4]          FLOAT (53)    NULL,
    [IdRubroEgr5]        VARCHAR (10)  NULL,
    [NRubroEgr5]         VARCHAR (10)  NULL,
    [ValorEgr5]          FLOAT (53)    NULL,
    [IdRubroEgr6]        VARCHAR (10)  NULL,
    [NRubroEgr6]         VARCHAR (10)  NULL,
    [ValorEgr6]          FLOAT (53)    NULL,
    [IdRubroEgr7]        VARCHAR (10)  NULL,
    [NRubroEgr7]         VARCHAR (10)  NULL,
    [ValorEgr7]          FLOAT (53)    NULL,
    [IdRubroEgr8]        VARCHAR (10)  NULL,
    [NRubroEgr8]         VARCHAR (10)  NULL,
    [ValorEgr8]          FLOAT (53)    NULL,
    [IdRubroEgr9]        VARCHAR (10)  NULL,
    [NRubroEgr9]         VARCHAR (10)  NULL,
    [ValorEgr9]          FLOAT (53)    NULL,
    [IdRubroEgr10]       VARCHAR (10)  NULL,
    [NRubroEgr10]        VARCHAR (10)  NULL,
    [ValorEgr10]         FLOAT (53)    NULL,
    [TotalEgr]           FLOAT (53)    NULL,
    [Total]              FLOAT (53)    NULL,
    [Fecha_Transac]      DATETIME      NOT NULL,
    CONSTRAINT [PK_tbROL_NominaGeneral] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdEmpleado] ASC, [IdNomina_Tipo] ASC, [IdNomina_TipoLiqui] ASC, [IdPeriodo] ASC, [nom_pc] ASC, [IdUsuario] ASC)
);

