CREATE TABLE [dbo].[tbROL_Rpt002] (
    [IdEmpresa]          INT           NOT NULL,
    [IdEmpleado]         NUMERIC (18)  NOT NULL,
    [IdPeriodo]          INT           NOT NULL,
    [IdRubro]            VARCHAR (20)  NOT NULL,
    [IdNomina_Tipo]      INT           NOT NULL,
    [IdNomina_TipoLiqui] INT           NOT NULL,
    [IdNovedad]          NUMERIC (18)  NOT NULL,
    [SecuenciaNovedad]   INT           NOT NULL,
    [IdPrestamo]         NUMERIC (18)  NOT NULL,
    [NunCouta]           NUMERIC (18)  NOT NULL,
    [IdDepartamento]     INT           NULL,
    [Valor]              FLOAT (53)    NOT NULL,
    [IdUsuario]          VARCHAR (30)  NOT NULL,
    [pe_nombreCompleto]  VARCHAR (200) NOT NULL,
    [Departamento]       NCHAR (60)    NULL,
    [pe_FechaFin]        SMALLDATETIME NOT NULL,
    [Fecha_Transac]      DATETIME      NULL,
    [em_nombre]          NCHAR (50)    NOT NULL,
    [nom_pc]             VARCHAR (50)  NOT NULL,
    [ru_descripcion]     VARCHAR (50)  NOT NULL,
    [ru_tipo]            CHAR (1)      NOT NULL,
    [dias_trabajo]       INT           NULL,
    [dias_vacaciones]    INT           NULL,
    [dias_maternidad]    INT           NULL,
    [totIng]             FLOAT (53)    NULL,
    [totEgr]             FLOAT (53)    NULL,
    [totalNeto]          FLOAT (53)    NULL,
    [secuencia]          INT           NOT NULL,
    [OrgCopy]            VARCHAR (20)  NULL,
    CONSTRAINT [PK_tbROL_Rpt002] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdEmpleado] ASC, [IdPeriodo] ASC, [IdRubro] ASC, [IdNomina_Tipo] ASC, [IdNomina_TipoLiqui] ASC, [IdNovedad] ASC, [SecuenciaNovedad] ASC, [IdPrestamo] ASC, [NunCouta] ASC, [IdUsuario] ASC, [nom_pc] ASC, [secuencia] ASC)
);

