//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATS_ventas
    {
        public int IdEmpresa { get; set; }
        public int IdPeriodo { get; set; }
        public int Secuencia { get; set; }
        public string tpIdCliente { get; set; }
        public string idCliente { get; set; }
        public string parteRel { get; set; }
        public string tipoCliente { get; set; }
        public string DenoCli { get; set; }
        public string tipoComprobante { get; set; }
        public string tipoEm { get; set; }
        public int numeroComprobantes { get; set; }
        public decimal baseNoGraIva { get; set; }
        public decimal baseImponible { get; set; }
        public decimal baseImpGrav { get; set; }
        public decimal montoIva { get; set; }
        public decimal montoIce { get; set; }
        public decimal valorRetIva { get; set; }
        public decimal valorRetRenta { get; set; }
        public string formaPago { get; set; }
        public string codEstab { get; set; }
        public decimal ventasEstab { get; set; }
        public decimal ivaComp { get; set; }
    }
}
