//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_CatalogoTipo
    {
        public ba_CatalogoTipo()
        {
            this.ba_Catalogo = new HashSet<ba_Catalogo>();
        }
    
        public string IdTipoCatalogo { get; set; }
        public string tc_Descripcion { get; set; }
    
        public virtual ICollection<ba_Catalogo> ba_Catalogo { get; set; }
    }
}
