//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_Talonario_cheques_x_banco
    {
        public int IdEmpresa { get; set; }
        public int IdBanco { get; set; }
        public string Num_cheque { get; set; }
        public Nullable<decimal> secuencia { get; set; }
        public bool Usado { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdEmpresa_cbtecble_Usado { get; set; }
        public Nullable<decimal> IdCbteCble_cbtecble_Usado { get; set; }
        public Nullable<int> IdTipoCbte_cbtecble_Usado { get; set; }
        public Nullable<System.DateTime> Fecha_uso { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string MotivoAnulacion { get; set; }
        public string IdUsuario_Anu { get; set; }
    
        public virtual ba_Banco_Cuenta ba_Banco_Cuenta { get; set; }
    }
}
