//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_cuotas_x_doc_det
    {
        public int IdEmpresa { get; set; }
        public decimal IdCuota { get; set; }
        public int Secuencia { get; set; }
        public int Num_cuota { get; set; }
        public System.DateTime Fecha_vcto_cuota { get; set; }
        public double Valor_cuota { get; set; }
        public string Observacion { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> IdEmpresa_op { get; set; }
        public Nullable<decimal> IdOrdenPago { get; set; }
        public Nullable<int> Secuencia_op { get; set; }
    
        public virtual cp_cuotas_x_doc cp_cuotas_x_doc { get; set; }
        public virtual cp_orden_pago_det cp_orden_pago_det { get; set; }
    }
}
