//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_orden_pago_formapago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cp_orden_pago_formapago()
        {
            this.cp_orden_pago = new HashSet<cp_orden_pago>();
            this.cp_orden_pago_det = new HashSet<cp_orden_pago_det>();
        }
    
        public string IdFormaPago { get; set; }
        public string descripcion { get; set; }
        public string IdTipoTransaccion { get; set; }
        public string CodModulo { get; set; }
        public Nullable<int> IdTipoMovi_caj { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cp_orden_pago> cp_orden_pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cp_orden_pago_det> cp_orden_pago_det { get; set; }
    }
}
