//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_SolicitudPago
    {
        public cp_SolicitudPago()
        {
            this.cp_SolicitudPagoDet = new HashSet<cp_SolicitudPagoDet>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdSolicitud { get; set; }
        public int IdSucursal { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal IdProveedor { get; set; }
        public string Concepto { get; set; }
        public bool Estado { get; set; }
        public double Valor { get; set; }
        public string Solicitante { get; set; }
        public string GiradoA { get; set; }
        public string IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string IdUsuarioAnulacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string MotivoAnulacion { get; set; }
    
        public virtual cp_proveedor cp_proveedor { get; set; }
        public virtual ICollection<cp_SolicitudPagoDet> cp_SolicitudPagoDet { get; set; }
    }
}
