//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_cbtecble_tipo
    {
        public ct_cbtecble_tipo()
        {
            this.ct_parametro = new HashSet<ct_parametro>();
            this.ct_parametro1 = new HashSet<ct_parametro>();
            this.ct_cbtecble = new HashSet<ct_cbtecble>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdTipoCbte { get; set; }
        public string CodTipoCbte { get; set; }
        public string tc_TipoCbte { get; set; }
        public string tc_Estado { get; set; }
        public string tc_Interno { get; set; }
        public string tc_Nemonico { get; set; }
        public int IdTipoCbte_Anul { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string MotiAnula { get; set; }
    
        public virtual ICollection<ct_parametro> ct_parametro { get; set; }
        public virtual ICollection<ct_parametro> ct_parametro1 { get; set; }
        public virtual ICollection<ct_cbtecble> ct_cbtecble { get; set; }
    }
}
