//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxc_liquidacion_comisiones
    {
        public cxc_liquidacion_comisiones()
        {
            this.cxc_liquidacion_comisiones_det = new HashSet<cxc_liquidacion_comisiones_det>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdLiquidacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public bool Estado { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaTransac { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> FechaUltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> FechaUltAnu { get; set; }
        public string MotivoAnulacion { get; set; }
    
        public virtual ICollection<cxc_liquidacion_comisiones_det> cxc_liquidacion_comisiones_det { get; set; }
    }
}
