//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxc_CatalogoTipo
    {
        public cxc_CatalogoTipo()
        {
            this.cxc_Catalogo = new HashSet<cxc_Catalogo>();
        }
    
        public string IdCatalogo_tipo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<cxc_Catalogo> cxc_Catalogo { get; set; }
    }
}
