//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_cliente_x_fa_Vendedor_x_sucursal
    {
        public int IdEmpresa { get; set; }
        public decimal IdCliente { get; set; }
        public int IdSucursal { get; set; }
        public int IdVendedor { get; set; }
        public string observacion { get; set; }
    
        public virtual fa_Vendedor fa_Vendedor { get; set; }
        public virtual fa_cliente fa_cliente { get; set; }
    }
}
