//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_CambioProductoDet
    {
        public fa_CambioProductoDet()
        {
            this.fa_CambioProductoDet_x_in_devolucion_inven = new HashSet<fa_CambioProductoDet_x_in_devolucion_inven>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdCambio { get; set; }
        public int Secuencia { get; set; }
        public decimal IdCbteVta { get; set; }
        public int SecuenciaFact { get; set; }
        public decimal IdProductoFact { get; set; }
        public decimal IdProductoCambio { get; set; }
        public double CantidadFact { get; set; }
        public double CantidadCambio { get; set; }
    
        public virtual fa_CambioProducto fa_CambioProducto { get; set; }
        public virtual fa_factura_det fa_factura_det { get; set; }
        public virtual ICollection<fa_CambioProductoDet_x_in_devolucion_inven> fa_CambioProductoDet_x_in_devolucion_inven { get; set; }
    }
}
