//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_factura_x_cxc_cobro_tipo
    {
        public int IdEmpresa_fa { get; set; }
        public int IdSucursal_fa { get; set; }
        public int IdBodega_fa { get; set; }
        public decimal IdCbteVta_fa { get; set; }
        public int Secuencia { get; set; }
        public string IdCobro_tipo { get; set; }
        public int IdEmpresa_cxc { get; set; }
        public int IdSucursal_cxc { get; set; }
        public decimal IdCobro_cxc { get; set; }
        public double Valor { get; set; }
    
        public virtual fa_factura fa_factura { get; set; }
    }
}
