//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_factura_x_in_Ing_Egr_Inven
    {
        public int IdEmpresa_fa { get; set; }
        public int IdSucursal_fa { get; set; }
        public int IdBodega_fa { get; set; }
        public decimal IdCbteVta_fa { get; set; }
        public int IdEmpresa_in_eg_x_inv { get; set; }
        public int IdSucursal_in_eg_x_inv { get; set; }
        public int IdMovi_inven_tipo_in_eg_x_inv { get; set; }
        public decimal IdNumMovi_in_eg_x_inv { get; set; }
        public string observacion { get; set; }
    
        public virtual fa_factura fa_factura { get; set; }
    }
}
