//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_factura_det_x_in_Ing_Egr_Inven_det
    {
        public int IdEmpresa_fa { get; set; }
        public int IdSucursal_fa { get; set; }
        public int IdBodega_fa { get; set; }
        public decimal IdCbteVta_fa { get; set; }
        public int Secuencia_fa { get; set; }
        public int IdEmpresa_eg { get; set; }
        public int IdSucursal_eg { get; set; }
        public int IdMovi_inven_tipo_eg { get; set; }
        public decimal IdNumMovi_eg { get; set; }
        public int Secuencia_eg { get; set; }
        public string Observacion { get; set; }
    }
}
