//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_TerminoPago
    {
        public fa_TerminoPago()
        {
            this.fa_TerminoPago_Distribucion = new HashSet<fa_TerminoPago_Distribucion>();
            this.fa_cliente = new HashSet<fa_cliente>();
            this.fa_proforma = new HashSet<fa_proforma>();
        }
    
        public string IdTerminoPago { get; set; }
        public string nom_TerminoPago { get; set; }
        public int Num_Coutas { get; set; }
        public int Dias_Vct { get; set; }
        public bool estado { get; set; }
    
        public virtual ICollection<fa_TerminoPago_Distribucion> fa_TerminoPago_Distribucion { get; set; }
        public virtual ICollection<fa_cliente> fa_cliente { get; set; }
        public virtual ICollection<fa_proforma> fa_proforma { get; set; }
    }
}
