//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_TerminoPago_Distribucion
    {
        public string IdTerminoPago { get; set; }
        public int Secuencia { get; set; }
        public int Num_Dias_Vcto { get; set; }
        public double Por_distribucion { get; set; }
    
        public virtual fa_TerminoPago fa_TerminoPago { get; set; }
    }
}
