//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class imp_gasto_x_ct_plancta
    {
        public int IdGasto_tipo { get; set; }
        public int IdEmpresa { get; set; }
        public string IdCtaCble { get; set; }
    
        public virtual imp_gasto imp_gasto { get; set; }
    }
}
