//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_CatalogoTipo
    {
        public in_CatalogoTipo()
        {
            this.in_Catalogo = new HashSet<in_Catalogo>();
        }
    
        public int IdCatalogo_tipo { get; set; }
        public string cod_Catalogo_tipo { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<in_Catalogo> in_Catalogo { get; set; }
    }
}
