//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_movi_inve_detalle_x_ct_cbtecble_det
    {
        public int IdEmpresa_inv { get; set; }
        public int IdSucursal_inv { get; set; }
        public int IdBodega_inv { get; set; }
        public int IdMovi_inven_tipo_inv { get; set; }
        public decimal IdNumMovi_inv { get; set; }
        public int Secuencia_inv { get; set; }
        public int IdEmpresa_ct { get; set; }
        public int IdTipoCbte_ct { get; set; }
        public decimal IdCbteCble_ct { get; set; }
        public int secuencia_ct { get; set; }
        public decimal Secuencial_reg { get; set; }
        public string observacion { get; set; }
    }
}
