//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_presentacion
    {
        public in_presentacion()
        {
            this.in_Producto = new HashSet<in_Producto>();
        }
    
        public int IdEmpresa { get; set; }
        public string IdPresentacion { get; set; }
        public string nom_presentacion { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<in_Producto> in_Producto { get; set; }
    }
}
