//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities_cuentas_por_pagar : DbContext
    {
        public Entities_cuentas_por_pagar()
            : base("name=Entities_cuentas_por_pagar")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cp_codigo_SRI_tipo> cp_codigo_SRI_tipo { get; set; }
        public virtual DbSet<cp_codigo_SRI> cp_codigo_SRI { get; set; }
        public virtual DbSet<cp_codigo_SRI_x_CtaCble> cp_codigo_SRI_x_CtaCble { get; set; }
        public virtual DbSet<cp_proveedor_clase> cp_proveedor_clase { get; set; }
        public virtual DbSet<cp_proveedor> cp_proveedor { get; set; }
        public virtual DbSet<vwcp_proveedor_consulta> vwcp_proveedor_consulta { get; set; }
    }
}
