//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities_inventario : DbContext
    {
        public Entities_inventario()
            : base("name=Entities_inventario")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<in_CatalogoTipo> in_CatalogoTipo { get; set; }
        public virtual DbSet<in_movi_inven_tipo> in_movi_inven_tipo { get; set; }
        public virtual DbSet<in_movi_inven_tipo_x_tb_bodega> in_movi_inven_tipo_x_tb_bodega { get; set; }
        public virtual DbSet<in_Catalogo> in_Catalogo { get; set; }
        public virtual DbSet<in_Marca> in_Marca { get; set; }
        public virtual DbSet<in_presentacion> in_presentacion { get; set; }
        public virtual DbSet<in_parametro> in_parametro { get; set; }
        public virtual DbSet<in_categorias> in_categorias { get; set; }
        public virtual DbSet<in_grupo> in_grupo { get; set; }
        public virtual DbSet<in_linea> in_linea { get; set; }
        public virtual DbSet<in_subgrupo> in_subgrupo { get; set; }
        public virtual DbSet<in_UnidadMedida> in_UnidadMedida { get; set; }
        public virtual DbSet<in_UnidadMedida_Equiv_conversion> in_UnidadMedida_Equiv_conversion { get; set; }
        public virtual DbSet<in_Producto> in_Producto { get; set; }
        public virtual DbSet<in_Motivo_Inven> in_Motivo_Inven { get; set; }
        public virtual DbSet<in_Producto_Composicion> in_Producto_Composicion { get; set; }
        public virtual DbSet<in_ProductoTipo> in_ProductoTipo { get; set; }
        public virtual DbSet<in_producto_x_tb_bodega> in_producto_x_tb_bodega { get; set; }
        public virtual DbSet<in_Ing_Egr_Inven> in_Ing_Egr_Inven { get; set; }
        public virtual DbSet<in_Ing_Egr_Inven_det> in_Ing_Egr_Inven_det { get; set; }
        public virtual DbSet<in_transferencia> in_transferencia { get; set; }
        public virtual DbSet<in_transferencia_det> in_transferencia_det { get; set; }
        public virtual DbSet<vwin_Transferencias> vwin_Transferencias { get; set; }
    }
}
