//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities_presupuesto : DbContext
    {
        public Entities_presupuesto()
            : base("name=Entities_presupuesto")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pre_rubro> pre_rubro { get; set; }
        public virtual DbSet<vwpre_rubro> vwpre_rubro { get; set; }
        public virtual DbSet<pre_Grupo> pre_Grupo { get; set; }
        public virtual DbSet<pre_Grupo_x_seg_usuario> pre_Grupo_x_seg_usuario { get; set; }
    }
}
