//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pre_Grupo_x_seg_usuario
    {
        public int IdEmpresa { get; set; }
        public int IdGrupo { get; set; }
        public int Secuencia { get; set; }
        public string IdUsuario { get; set; }
        public bool AsignaCuentas { get; set; }
    
        public virtual pre_Grupo pre_Grupo { get; set; }
    }
}
