//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_FormulaHorasRecargo
    {
        public int IdEmpresa { get; set; }
        public double Dividendo { get; set; }
        public double Divisor { get; set; }
        public double PorcentajeRecargo { get; set; }
    }
}
