//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_HorasProfesores
    {
        public ro_HorasProfesores()
        {
            this.ro_HorasProfesores_det = new HashSet<ro_HorasProfesores_det>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdCarga { get; set; }
        public int IdNomina { get; set; }
        public int IdNominaTipo { get; set; }
        public int IdPeriodo { get; set; }
        public System.DateTime FechaCarga { get; set; }
        public string Observacion { get; set; }
        public string IdUsuario { get; set; }
        public bool Estado { get; set; }
        public System.DateTime Fecha_Transac { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string MotiAnula { get; set; }
    
        public virtual ICollection<ro_HorasProfesores_det> ro_HorasProfesores_det { get; set; }
        public virtual ro_Nomina_Tipoliqui ro_Nomina_Tipoliqui { get; set; }
    }
}
