//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_novedad_x_empleado
    {
        public int IdEmpresa { get; set; }
        public decimal IdTransaccion { get; set; }
        public int IdEmpresa_Emp_Novedad { get; set; }
        public decimal IdNovedad_Emp_Novedad { get; set; }
        public decimal IdEmpleado_Emp_Novedad { get; set; }
        public string Observacion { get; set; }
        public string estado { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdNomina_Tipo { get; set; }
        public int IdNomina_TipoLiqui { get; set; }
        public string IdRubro { get; set; }
    }
}
