//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_novedad_x_empleado
    {
        public int IdEmpresa { get; set; }
        public decimal IdTransaccion { get; set; }
        public int IdEmpresa_Emp_Novedad { get; set; }
        public decimal IdNovedad_Emp_Novedad { get; set; }
        public decimal IdEmpleado_Emp_Novedad { get; set; }
        public string Observacion { get; set; }
        public string estado { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdNomina_Tipo { get; set; }
        public int IdNomina_TipoLiqui { get; set; }
        public string IdRubro { get; set; }
    }
}
