//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_parametro_contable_x_Nomina_Tipoliqui_Sueldo_x_Pagar
    {
        public int IdEmpresa { get; set; }
        public int IdNomina { get; set; }
        public int IdNominaTipo { get; set; }
        public string IdCtaCble { get; set; }
        public string Observacion { get; set; }
        public Nullable<decimal> IdTipoFlujo { get; set; }
    
        public virtual ro_Nomina_Tipoliqui ro_Nomina_Tipoliqui { get; set; }
    }
}
