//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_rubros_calculados
    {
        public int IdEmpresa { get; set; }
        public string IdRubro_dias_trabajados { get; set; }
        public string IdRubro_tot_ing { get; set; }
        public string IdRubro_tot_egr { get; set; }
        public string IdRubro_iess_perso { get; set; }
        public string IdRubro_sueldo { get; set; }
        public string IdRubro_tot_pagar { get; set; }
        public string IdRubro_aporte_patronal { get; set; }
        public string IdRubro_fondo_reserva { get; set; }
        public string IdRubro_prov_vac { get; set; }
        public string IdRubro_prov_DIII { get; set; }
        public string IdRubro_prov_DIV { get; set; }
        public string IdRubro_prov_FR { get; set; }
        public string IdRubro_DIII { get; set; }
        public string IdRubro_DIV { get; set; }
        public string IdRubro_IR { get; set; }
        public string IdRubro_FR { get; set; }
    
        public virtual ro_rubro_tipo ro_rubro_tipo { get; set; }
        public virtual ro_rubro_tipo ro_rubro_tipo1 { get; set; }
        public virtual ro_rubro_tipo ro_rubro_tipo2 { get; set; }
        public virtual ro_rubro_tipo ro_rubro_tipo3 { get; set; }
        public virtual ro_rubro_tipo ro_rubro_tipo4 { get; set; }
        public virtual ro_rubro_tipo ro_rubro_tipo5 { get; set; }
    }
}
