//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_Menu_Pagina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seg_Menu_Pagina()
        {
            this.seg_Menu_Grupo = new HashSet<seg_Menu_Grupo>();
        }
    
        public string Codigo_Pagina { get; set; }
        public string Descripcion { get; set; }
        public bool Visible { get; set; }
        public bool Expanded { get; set; }
        public int ImageIndex { get; set; }
        public string ImageAlign { get; set; }
        public string Codigo_Categoria { get; set; }
        public int position { get; set; }
    
        public virtual seg_Menu_Categoria seg_Menu_Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seg_Menu_Grupo> seg_Menu_Grupo { get; set; }
    }
}
