//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_usuario_x_tb_sis_reporte
    {
        public string IdUsuario { get; set; }
        public string CodReporte { get; set; }
        public string observacion { get; set; }
    
        public virtual seg_usuario seg_usuario { get; set; }
    }
}
