//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_Menu_Grupo_x_seg_Menu_Item
    {
        public string Codigo_Item { get; set; }
        public string Codigo_Grupo { get; set; }
        public string observacion { get; set; }
    
        public virtual seg_Menu_Grupo seg_Menu_Grupo { get; set; }
        public virtual seg_Menu_Item seg_Menu_Item { get; set; }
    }
}
