//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_banco
    {
        public tb_banco()
        {
            this.tb_banco_procesos_bancarios_x_empresa = new HashSet<tb_banco_procesos_bancarios_x_empresa>();
            this.tb_persona = new HashSet<tb_persona>();
        }
    
        public int IdBanco { get; set; }
        public string ba_descripcion { get; set; }
        public string Estado { get; set; }
        public string CodigoLegal { get; set; }
        public bool TieneFormatoTransferencia { get; set; }
    
        public virtual ICollection<tb_banco_procesos_bancarios_x_empresa> tb_banco_procesos_bancarios_x_empresa { get; set; }
        public virtual ICollection<tb_persona> tb_persona { get; set; }
    }
}
