//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Catalogo
    {
        public tb_Catalogo()
        {
            this.tb_persona = new HashSet<tb_persona>();
            this.tb_persona1 = new HashSet<tb_persona>();
            this.tb_persona2 = new HashSet<tb_persona>();
            this.tb_persona3 = new HashSet<tb_persona>();
            this.tb_persona4 = new HashSet<tb_persona>();
            this.tb_persona5 = new HashSet<tb_persona>();
            this.tb_persona6 = new HashSet<tb_persona>();
        }
    
        public string CodCatalogo { get; set; }
        public int IdTipoCatalogo { get; set; }
        public int IdCatalogo { get; set; }
        public string ca_descripcion { get; set; }
        public string ca_estado { get; set; }
        public int ca_orden { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transaccion { get; set; }
        public string IdUsuarioUltModi { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string MotivoAnulacion { get; set; }
    
        public virtual tb_CatalogoTipo tb_CatalogoTipo { get; set; }
        public virtual ICollection<tb_persona> tb_persona { get; set; }
        public virtual ICollection<tb_persona> tb_persona1 { get; set; }
        public virtual ICollection<tb_persona> tb_persona2 { get; set; }
        public virtual ICollection<tb_persona> tb_persona3 { get; set; }
        public virtual ICollection<tb_persona> tb_persona4 { get; set; }
        public virtual ICollection<tb_persona> tb_persona5 { get; set; }
        public virtual ICollection<tb_persona> tb_persona6 { get; set; }
    }
}
