//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_parametro
    {
        public int IdEmpresa { get; set; }
        public string IdCod_Impuesto { get; set; }
        public double Porcentaje { get; set; }
        public bool EsMultiSucursal { get; set; }
    
        public virtual tb_sis_Impuesto tb_sis_Impuesto { get; set; }
    }
}
