//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_log_error
    {
        public int IdEmpresa { get; set; }
        public decimal IdError { get; set; }
        public string DescripcionError { get; set; }
        public string Modulo { get; set; }
        public string Accion { get; set; }
    }
}
