//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_Impuesto_Tipo
    {
        public tb_sis_Impuesto_Tipo()
        {
            this.tb_sis_Impuesto = new HashSet<tb_sis_Impuesto>();
        }
    
        public string IdTipoImpuesto { get; set; }
        public string nom_tipoImpuesto { get; set; }
    
        public virtual ICollection<tb_sis_Impuesto> tb_sis_Impuesto { get; set; }
    }
}
