//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TransaccionesAutorizadas
    {
        public int IdEmpresa { get; set; }
        public decimal IdTransaccion { get; set; }
        public string IdUsuarioLog { get; set; }
        public string IdUsuarioAut { get; set; }
        public string Observacion { get; set; }
        public System.DateTime FechaTransaccion { get; set; }
    }
}
