//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_usuario_ftp
    {
        public int Id { get; set; }
        public string ftp_usuario { get; set; }
        public string ftp_contrasenia { get; set; }
        public string ftp_url { get; set; }
    }
}
