//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcp_nota_DebCre
    {
        public int IdEmpresa { get; set; }
        public decimal IdCbteCble_Nota { get; set; }
        public int IdTipoCbte_Nota { get; set; }
        public string DebCre { get; set; }
        public string IdTipoNota { get; set; }
        public decimal IdProveedor { get; set; }
        public int IdSucursal { get; set; }
        public System.DateTime cn_fecha { get; set; }
        public Nullable<System.DateTime> Fecha_contable { get; set; }
        public System.DateTime cn_Fecha_vcto { get; set; }
        public string cn_serie1 { get; set; }
        public string cn_serie2 { get; set; }
        public string cn_Nota { get; set; }
        public string cn_observacion { get; set; }
        public double cn_subtotal_iva { get; set; }
        public double cn_subtotal_siniva { get; set; }
        public double cn_baseImponible { get; set; }
        public double cn_Por_iva { get; set; }
        public double cn_valoriva { get; set; }
        public double cn_Ice_base { get; set; }
        public double cn_Ice_por { get; set; }
        public double cn_Ice_valor { get; set; }
        public double cn_Serv_por { get; set; }
        public double cn_Serv_valor { get; set; }
        public decimal cn_BaseSeguro { get; set; }
        public decimal cn_total { get; set; }
        public string cn_vaCoa { get; set; }
        public string cn_Autorizacion { get; set; }
        public string cn_Autorizacion_Imprenta { get; set; }
        public string cn_num_doc_modificado { get; set; }
        public Nullable<int> IdCod_ICE { get; set; }
        public string IdTipoServicio { get; set; }
        public Nullable<int> IdIden_credito { get; set; }
        public string IdCtaCble_Acre { get; set; }
        public string IdCtaCble_IVA { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> IdCbteCble_Anulacion { get; set; }
        public Nullable<int> IdTipoCbte_Anulacion { get; set; }
        public string cn_tipoLocacion { get; set; }
        public string cod_nota { get; set; }
        public Nullable<System.DateTime> fecha_autorizacion { get; set; }
        public string PagoSujetoRetencion { get; set; }
        public string ConvenioTributacion { get; set; }
        public string PaisPago { get; set; }
        public string PagoLocExt { get; set; }
        public string IdCentroCosto { get; set; }
        public Nullable<decimal> IdTipoFlujo { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string pe_razonSocial { get; set; }
    }
}
