//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcp_codigo_SRI
    {
        public Nullable<int> IdEmpresa { get; set; }
        public int IdCodigo_SRI { get; set; }
        public string codigoSRI { get; set; }
        public string co_codigoBase { get; set; }
        public string co_descripcion { get; set; }
        public double co_porRetencion { get; set; }
        public System.DateTime co_f_valides_desde { get; set; }
        public System.DateTime co_f_valides_hasta { get; set; }
        public string co_estado { get; set; }
        public string IdTipoSRI { get; set; }
        public string IdCtaCble { get; set; }
    }
}
