//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_cliente_contactos
    {
        public int IdEmpresa { get; set; }
        public decimal IdCliente { get; set; }
        public int IdContacto { get; set; }
        public string Nombres { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Correo { get; set; }
        public string Direccion { get; set; }
        public string IdCiudad { get; set; }
        public string IdParroquia { get; set; }
        public string nom_parroquia { get; set; }
        public string Descripcion_Ciudad { get; set; }
    }
}
