//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_factura
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdCbteVta { get; set; }
        public string vt_NumFactura { get; set; }
        public System.DateTime vt_fecha { get; set; }
        public string Nombres { get; set; }
        public string Ve_Vendedor { get; set; }
        public Nullable<double> vt_Subtotal0 { get; set; }
        public Nullable<double> vt_SubtotalIVA { get; set; }
        public Nullable<double> vt_iva { get; set; }
        public Nullable<double> vt_total { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> esta_impresa { get; set; }
        public Nullable<int> IdEmpresa_in_eg_x_inv { get; set; }
        public Nullable<int> IdSucursal_in_eg_x_inv { get; set; }
        public Nullable<int> IdMovi_inven_tipo_in_eg_x_inv { get; set; }
        public Nullable<decimal> IdNumMovi_in_eg_x_inv { get; set; }
        public Nullable<System.DateTime> Fecha_Autorizacion { get; set; }
        public string vt_autorizacion { get; set; }
    }
}
