//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWFAC_009
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdGuiaRemision { get; set; }
        public string vt_tipoDoc { get; set; }
        public string vt_NumFactura { get; set; }
        public string vt_autorizacion { get; set; }
        public System.DateTime gi_FechaInicioTraslado { get; set; }
        public System.DateTime gi_FechaFinTraslado { get; set; }
        public string Num_declaracion_aduanera { get; set; }
        public string MotivoTraslado { get; set; }
        public string Direccion_Origen { get; set; }
        public string Direccion_Destino { get; set; }
        public string CedulaCliente { get; set; }
        public string NomCliente { get; set; }
        public string CedulaTransportista { get; set; }
        public string NombreTransportista { get; set; }
        public string placa { get; set; }
        public string RucEmpresa { get; set; }
        public double gi_cantidad { get; set; }
        public string pr_descripcion { get; set; }
    }
}
