//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwimp_orden_compra_ext_recepcion_det
    {
        public int IdEmpresa { get; set; }
        public decimal IdRecepcion { get; set; }
        public int secuencia { get; set; }
        public decimal IdProducto { get; set; }
        public int IdEmpresa_oc { get; set; }
        public decimal IdOrdenCompra_ext { get; set; }
        public int Secuencia_oc { get; set; }
        public double cantidad { get; set; }
        public string Observacion { get; set; }
        public double od_cantidad { get; set; }
        public double od_cantidad_recepcion { get; set; }
        public string pr_descripcion { get; set; }
        public Nullable<System.DateTime> lote_fecha_fab { get; set; }
        public Nullable<System.DateTime> lote_fecha_vcto { get; set; }
        public string lote_num_lote { get; set; }
        public string IdUnidadMedida { get; set; }
    }
}
