//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwrdep_IngrEgr_x_Empleado
    {
        public int IdEmpresa { get; set; }
        public decimal IdEmpleado { get; set; }
        public Nullable<int> pe_anio { get; set; }
        public string Su_CodigoEstablecimiento { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string pe_nombre { get; set; }
        public string pe_apellido { get; set; }
        public Nullable<double> Sueldo { get; set; }
        public Nullable<decimal> FondosReserva { get; set; }
        public Nullable<decimal> DecimoTercerSueldo { get; set; }
        public Nullable<double> DecimoCuartoSueldo { get; set; }
        public Nullable<decimal> Vacaciones { get; set; }
        public Nullable<double> AportePErsonal { get; set; }
        public double GastoAlimentacion { get; set; }
        public double GastoEucacion { get; set; }
        public double GastoSalud { get; set; }
        public double GastoVestimenta { get; set; }
        public double GastoVivienda { get; set; }
        public double Utilidades { get; set; }
        public Nullable<double> IngresoVarios { get; set; }
    }
}
