//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWROL_024
    {
        public int IdEmpresa { get; set; }
        public decimal IdRol { get; set; }
        public decimal IdEmpleado { get; set; }
        public int IdNominaTipoLiqui { get; set; }
        public int IdNominaTipo { get; set; }
        public string NomNomina { get; set; }
        public string NomNominaTipo { get; set; }
        public string pe_nombreCompleto { get; set; }
        public int IdPeriodo { get; set; }
        public System.DateTime pe_FechaIni { get; set; }
        public System.DateTime pe_FechaFin { get; set; }
        public double Valor { get; set; }
        public int IdSucursal { get; set; }
        public string Su_Descripcion { get; set; }
        public string pe_cedulaRuc { get; set; }
        public double Dias { get; set; }
    }
}
