//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_nomina_x_horas_extras_det
    {
        public int IdEmpresa { get; set; }
        public int IdHorasExtras { get; set; }
        public decimal IdEmpleado { get; set; }
        public int IdCalendario { get; set; }
        public decimal IdTurno { get; set; }
        public decimal IdHorario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.TimeSpan> time_entrada1 { get; set; }
        public Nullable<System.TimeSpan> time_entrada2 { get; set; }
        public Nullable<System.TimeSpan> time_salida1 { get; set; }
        public Nullable<System.TimeSpan> time_salida2 { get; set; }
        public double hora_extra25 { get; set; }
        public double hora_extra50 { get; set; }
        public double hora_extra100 { get; set; }
        public double hora_atraso { get; set; }
        public double hora_temprano { get; set; }
        public double hora_trabajada { get; set; }
        public bool es_HorasExtrasAutorizadas { get; set; }
        public string Horario { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public string tu_descripcion { get; set; }
        public string ca_descripcion { get; set; }
        public string pe_cedulaRuc { get; set; }
    }
}
