//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWROL_003
    {
        public int IdEmpresa { get; set; }
        public decimal IdEmpleado { get; set; }
        public decimal IdPersona { get; set; }
        public decimal IdNovedad { get; set; }
        public System.DateTime FechaPago { get; set; }
        public double Valor { get; set; }
        public System.DateTime Fecha_Transac { get; set; }
        public string ca_descripcion { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string DescripcionProcesoNomina { get; set; }
        public string Observacion { get; set; }
        public string ru_descripcion { get; set; }
        public string EstadoCobro { get; set; }
    }
}
