//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWROL_009
    {
        public string CedulaRuc { get; set; }
        public string NombreCompleto { get; set; }
        public string IdRubro { get; set; }
        public System.DateTime FechaPago { get; set; }
        public double Valor { get; set; }
        public string EstadoCobro { get; set; }
        public string RubroDescripcion { get; set; }
        public string Division { get; set; }
        public string Departamento { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdEmpleado { get; set; }
        public Nullable<int> IdDivision { get; set; }
        public string CodigoEmpleado { get; set; }
        public int IdDepartamento { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public Nullable<double> Num_Horas { get; set; }
        public string ca_descripcion { get; set; }
    }
}
