//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_horario_planificacion_det
    {
        public Nullable<long> Secuencia { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdEmpleado { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string ca_descripcion { get; set; }
        public string ar_descripcion { get; set; }
        public string di_descripcion { get; set; }
        public string de_descripcion { get; set; }
        public string Su_Descripcion { get; set; }
        public Nullable<int> IdNomina { get; set; }
        public int IdSucursal { get; set; }
        public int IdDepartamento { get; set; }
        public int IdArea { get; set; }
        public int IdDivision { get; set; }
        public int IdCargo { get; set; }
        public Nullable<decimal> IdPlanificacion { get; set; }
        public Nullable<decimal> IdHorario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> IdCalendario { get; set; }
    }
}
