//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_EmpleadoNovedadCargaMasiva
    {
        public int IdEmpresa { get; set; }
        public decimal IdCarga { get; set; }
        public int IdNomina { get; set; }
        public int IdNominaTipo { get; set; }
        public int IdSucursal { get; set; }
        public System.DateTime FechaCarga { get; set; }
        public string Observacion { get; set; }
        public string IdRubro { get; set; }
        public string IdUsuario { get; set; }
        public bool Estado { get; set; }
        public string ru_descripcion { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionProcesoNomina { get; set; }
    }
}
