//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_SancionesPorMarcaciones_x_novedad
    {
        public int IdEmpresa { get; set; }
        public int IdAjuste { get; set; }
        public int Secuencia { get; set; }
        public decimal IdNovedad { get; set; }
        public int IdEmpresa_nov { get; set; }
        public decimal IdEmpleado { get; set; }
        public int IdNomina_Tipo { get; set; }
        public int IdNomina_TipoLiqui { get; set; }
        public double Valor { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string em_codigo { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public string pe_nombreCompleto { get; set; }
    }
}
