//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwtb_comprobantes_no_autorizados
    {
        public int IdEmpresa { get; set; }
        public string Tipo_documento { get; set; }
        public decimal IdCbteVta { get; set; }
        public string vt_serie1 { get; set; }
        public string vt_serie2 { get; set; }
        public string DocumentoDoc { get; set; }
        public string Documento { get; set; }
        public System.DateTime vt_fecha { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string vt_Observacion { get; set; }
        public int IdSucursal { get; set; }
    }
}
